-- Deploy schemas/my-schema/procedures/kitchen_sink to pg
-- requires: schemas/my-schema/schema
-- requires: schemas/other-schema/schema
-- made with mass-deploy

-- Kitchen sink fixture: every combinatorial way of having schemas
-- in qualified and unqualified positions across all node types.

BEGIN;

-- =============================================================================
-- 1. CREATE SCHEMA
-- =============================================================================
CREATE SCHEMA "my-schema";
CREATE SCHEMA "other-schema";

-- =============================================================================
-- 2. GRANT / REVOKE ON SCHEMA
-- =============================================================================
GRANT USAGE ON SCHEMA "my-schema" TO authenticated_role;
GRANT CREATE ON SCHEMA "other-schema" TO admin_role;
REVOKE ALL ON SCHEMA "my-schema" FROM public;

-- =============================================================================
-- 3. ALTER DEFAULT PRIVILEGES IN SCHEMA
-- =============================================================================
ALTER DEFAULT PRIVILEGES IN SCHEMA "my-schema" GRANT SELECT ON TABLES TO authenticated_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA "other-schema" GRANT EXECUTE ON FUNCTIONS TO admin_role;

-- =============================================================================
-- 4. SET search_path
-- =============================================================================
SET search_path TO "my-schema", public;

-- =============================================================================
-- 5. CREATE TABLE (CreateStmt) with schema-qualified names
--    Tests: CreateStmt.relation, ColumnDef.typeName, Constraint FK pktable
-- =============================================================================
CREATE TABLE "my-schema".users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id bigint,
  username text NOT NULL,
  email text NOT NULL,
  status "my-schema".user_status_type DEFAULT 'active',
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE "other-schema".audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name text NOT NULL,
  record_id bigint NOT NULL,
  action text NOT NULL,
  changed_by bigint REFERENCES "my-schema".users(id),
  changed_at timestamptz DEFAULT now()
);

-- =============================================================================
-- 6. CREATE TYPE / ENUM / DOMAIN
--    Tests: CreateEnumStmt, CreateDomainStmt, CompositeTypeStmt
-- =============================================================================
CREATE TYPE "my-schema".user_status_type AS ENUM ('active', 'inactive', 'suspended');
CREATE TYPE "other-schema".severity_level AS ENUM ('low', 'medium', 'high', 'critical');

CREATE DOMAIN "my-schema".positive_int AS integer CHECK (VALUE > 0);
CREATE DOMAIN "other-schema".email_address AS text CHECK (VALUE ~* '^[^@]+@[^@]+\.[^@]+$');

CREATE TYPE "my-schema".address_type AS (
  street text,
  city text,
  zip text
);

-- =============================================================================
-- 7. ALTER TYPE / ENUM / DOMAIN
-- =============================================================================
ALTER TYPE "my-schema".user_status_type ADD VALUE 'pending';
ALTER DOMAIN "my-schema".positive_int SET NOT NULL;

-- =============================================================================
-- 8. INSERT INTO (InsertStmt)
-- =============================================================================
INSERT INTO "my-schema".users (username, email) VALUES ('admin', 'admin@example.com');
INSERT INTO "other-schema".audit_log (table_name, record_id, action, changed_by)
  VALUES ('users', 1, 'INSERT', 1);

-- =============================================================================
-- 9. SELECT with schema-qualified references (RangeVar, TypeCast)
-- =============================================================================
SELECT
  u.id,
  u.username,
  u.email,
  u.status::"my-schema".user_status_type,
  u.metadata::text,
  NULL::"my-schema".address_type
FROM "my-schema".users u
WHERE u.status = 'active'
ORDER BY u.created_at;

SELECT
  a.id,
  a.action,
  u.username
FROM "other-schema".audit_log a
JOIN "my-schema".users u ON u.id = a.changed_by;

-- =============================================================================
-- 10. UPDATE / DELETE with schema-qualified tables
--     Tests: UpdateStmt.relation, DeleteStmt.relation
-- =============================================================================
UPDATE "my-schema".users SET status = 'inactive' WHERE username = 'admin';
DELETE FROM "other-schema".audit_log WHERE action = 'INSERT';

-- =============================================================================
-- 11. CREATE INDEX (IndexStmt)
--     Tests: IndexStmt.relation
-- =============================================================================
CREATE INDEX idx_users_email ON "my-schema".users (email);
CREATE INDEX idx_audit_action ON "other-schema".audit_log (action);

-- =============================================================================
-- 12. DROP SCHEMA
-- =============================================================================
DROP SCHEMA IF EXISTS "my-schema" CASCADE;

-- =============================================================================
-- 13. COMMENT ON (CommentStmt) - various object types
-- =============================================================================
COMMENT ON TABLE "my-schema".users IS 'Main users table';
COMMENT ON COLUMN "my-schema".users.email IS 'User email address';
COMMENT ON FUNCTION "my-schema".get_user_by_id(bigint) IS 'Fetch user by primary key';

-- =============================================================================
-- 14. CREATE TRIGGER (CreateTrigStmt)
--     Tests: CreateTrigStmt.relation, CreateTrigStmt.funcname
-- =============================================================================
CREATE TRIGGER trg_audit_insert
  AFTER INSERT ON "my-schema".users
  FOR EACH ROW
  EXECUTE FUNCTION "other-schema".log_change();

CREATE TRIGGER trg_audit_update
  AFTER UPDATE ON "my-schema".users
  FOR EACH ROW
  EXECUTE PROCEDURE "my-schema".on_user_update();

-- =============================================================================
-- 15. ALTER TABLE SET SCHEMA (AlterObjectSchemaStmt)
-- =============================================================================
ALTER TABLE "my-schema".users SET SCHEMA "other-schema";

-- =============================================================================
-- 16. Schema-qualified function calls in expressions (FuncCall)
-- =============================================================================
SELECT "my-schema".get_user_by_id(1);
SELECT "other-schema".compute_severity('high');

-- =============================================================================
-- 17. CREATE FUNCTION — comprehensive PL/pgSQL function
--     This single function tests ALL PL/pgSQL-specific schema patterns:
--     - Schema-qualified function name
--     - Schema-qualified return type
--     - DECLARE with schema-qualified variable types (both schemas)
--     - SELECT FROM schema-qualified table
--     - Cross-schema references in body
-- =============================================================================
CREATE FUNCTION "my-schema".kitchen_sink_fn(
  user_id bigint
) RETURNS "my-schema".users AS $$
DECLARE
  v_user "my-schema".users;
  v_status "my-schema".user_status_type;
  v_addr "my-schema".address_type;
  v_severity "other-schema".severity_level;
  v_audit_id bigint;
BEGIN
  SELECT * INTO v_user
  FROM "my-schema".users
  WHERE id = user_id;

  v_status := v_user.status;

  INSERT INTO "other-schema".audit_log (user_id)
  VALUES (v_user.id)
  RETURNING id INTO v_audit_id;

  RETURN v_user;
END;
$$ LANGUAGE plpgsql STABLE;

-- =============================================================================
-- 17b. Second PL/pgSQL function in the same file (multi-function support)
--     - Trigger function: conditional RETURN NEW, no explicit final return
--     - Verifies each function keeps its own body and no implicit RETURN;
--       is emitted (invalid in trigger functions)
-- =============================================================================
CREATE FUNCTION "other-schema".tg_audit_users() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO "other-schema".audit_log (user_id)
    VALUES (NEW.id);
    RETURN NEW;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 17c. Third PL/pgSQL function: cursor/exception/RAISE edge cases
--     - SCROLL cursor declaration (option must stay on the declaration)
--     - MOVE/FETCH with explicit counts and FIRST/LAST directions
--     - SQLSTATE exception condition
--     - Bare RAISE re-throw
--     - Array element assignment target
-- =============================================================================
CREATE FUNCTION "my-schema".cursor_edge_cases() RETURNS int AS $$
DECLARE
  scan_cursor SCROLL CURSOR FOR
    SELECT id FROM "my-schema".users ORDER BY id;
  ids int[] := ARRAY[0, 0, 0];
  current_id int;
BEGIN
  OPEN scan_cursor;
  MOVE FORWARD 2 FROM scan_cursor;
  FETCH PRIOR FROM scan_cursor INTO current_id;
  MOVE LAST IN scan_cursor;
  CLOSE scan_cursor;
  ids[1] := current_id;
  RETURN ids[1];
EXCEPTION
  WHEN unique_violation OR SQLSTATE '23503' THEN
    RAISE;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 18. CREATE VIEW (ViewStmt)
--     Tests: ViewStmt.view
-- =============================================================================
CREATE VIEW "my-schema".active_users AS
  SELECT id, username, email FROM "my-schema".users WHERE status = 'active';

-- =============================================================================
-- 19. ALTER TABLE ADD COLUMN (AlterTableStmt)
--     Tests: AlterTableStmt.relation
-- =============================================================================
ALTER TABLE "my-schema".users ADD COLUMN bio text;
ALTER TABLE "other-schema".audit_log ADD COLUMN ip_address inet;

-- =============================================================================
-- 20. CREATE SEQUENCE / ALTER SEQUENCE (CreateSeqStmt, AlterSeqStmt)
--     Tests: CreateSeqStmt.sequence, AlterSeqStmt.sequence, AlterSeqStmt OWNED BY
-- =============================================================================
CREATE SEQUENCE "my-schema".users_id_seq;
ALTER SEQUENCE "my-schema".users_id_seq OWNED BY "my-schema".users.id;

-- =============================================================================
-- 21. CREATE POLICY (CreatePolicyStmt)
--     Tests: CreatePolicyStmt.table
-- =============================================================================
CREATE POLICY users_select_policy ON "my-schema".users FOR SELECT USING (true);
CREATE POLICY audit_insert_policy ON "other-schema".audit_log FOR INSERT WITH CHECK (true);

-- =============================================================================
-- 22. CREATE RULE (RuleStmt)
--     Tests: RuleStmt.relation
-- =============================================================================
CREATE RULE notify_insert AS ON INSERT TO "my-schema".users DO NOTHING;

-- =============================================================================
-- 23. CLUSTER (ClusterStmt)
--     Tests: ClusterStmt.relation
-- =============================================================================
CLUSTER "my-schema".users USING idx_users_email;

-- =============================================================================
-- 24. VACUUM / ANALYZE (VacuumRelation)
--     Tests: VacuumRelation.relation
-- =============================================================================
VACUUM "my-schema".users;
ANALYZE "other-schema".audit_log;

-- =============================================================================
-- 25. Verify function calls (string literal patterns)
-- =============================================================================
SELECT assert_schema('my-schema'::regnamespace);
SELECT assert_table('my-schema.users'::regclass);
SELECT assert_function('my-schema.get_user_by_id(uuid)'::regprocedure);
SELECT assert_trigger('my-schema.users'::regclass, 'trg_audit_insert', 'my-schema.tg_audit'::regproc, 5);
SELECT assert_type('my-schema.user_status_type'::regtype);
SELECT assert_domain('my-schema.positive_int'::regtype, 'int4'::regtype);

-- =============================================================================
-- 26. JSON string values with schema names
-- =============================================================================
SELECT '{"schema":"my-schema"}'::jsonb;
SELECT '{"source":"other-schema"}'::jsonb;

-- =============================================================================
-- 27. MERGE (MergeStmt / MergeWhenClause)
--     Tests: MergeStmt.relation, sourceRelation, mergeWhenClauses
-- =============================================================================
MERGE INTO "my-schema".users u
USING "other-schema".audit_log s
ON u.id = s.id
WHEN MATCHED THEN
  UPDATE SET email = s.action
WHEN NOT MATCHED THEN
  INSERT (id, email) VALUES (s.id, s.action);

-- =============================================================================
-- 28. SECURITY LABEL (SecLabelStmt)
--     Tests: SecLabelStmt.object qualified names
-- =============================================================================
SECURITY LABEL FOR anon ON COLUMN "my-schema".users.email IS 'MASKED WITH FUNCTION anon.fake_email()';

-- =============================================================================
-- 29. GRANT / REVOKE ... IN SCHEMA (GrantStmt ACL_TARGET_ALL_IN_SCHEMA)
-- =============================================================================
GRANT SELECT ON ALL TABLES IN SCHEMA "my-schema" TO PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA "other-schema" FROM PUBLIC;

-- =============================================================================
-- 30. ALTER ... SET SCHEMA (AlterObjectSchemaStmt)
-- =============================================================================
ALTER TABLE "my-schema".users SET SCHEMA "other-schema";
ALTER TYPE "my-schema".user_status_type SET SCHEMA "other-schema";

-- =============================================================================
-- 31. DO block (DoStmt body transformation)
-- =============================================================================
DO $$
BEGIN
  PERFORM "my-schema".get_user_by_id('00000000-0000-0000-0000-000000000000'::uuid);
END;
$$;

-- =============================================================================
-- 32. Array-typed composite DECLARE variables (array bounds preservation)
-- =============================================================================
CREATE FUNCTION "my-schema".cache_users()
RETURNS void AS $$
DECLARE
  cached "my-schema".users[];
  current_user_row "my-schema".users;
BEGIN
  SELECT * INTO current_user_row FROM "my-schema".users LIMIT 1;
  cached := array_fill(current_user_row, ARRAY[1]);
END;
$$ LANGUAGE plpgsql;

COMMIT;
