-- Deploy schemas/my_schema/procedures/kitchen_sink to pg
-- requires: schemas/my_schema/schema
-- requires: schemas/other_schema/schema
-- made with mass-deploy

-- Kitchen sink fixture: every combinatorial way of having schemas
-- in qualified and unqualified positions across all node types.

BEGIN;

CREATE SCHEMA my_schema;

CREATE SCHEMA other_schema;

GRANT USAGE ON SCHEMA my_schema TO authenticated_role;

GRANT CREATE ON SCHEMA other_schema TO admin_role;

REVOKE ALL ON SCHEMA my_schema FROM PUBLIC RESTRICT;

ALTER DEFAULT PRIVILEGES IN SCHEMA my_schema
  GRANT SELECT ON TABLES TO authenticated_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA other_schema
  GRANT EXECUTE ON FUNCTIONS TO admin_role;

SET search_path TO my_schema, public;

CREATE TABLE my_schema.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id bigint,
  username text NOT NULL,
  email text NOT NULL,
  status my_schema.user_status_type DEFAULT 'active',
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE other_schema.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name text NOT NULL,
  record_id bigint NOT NULL,
  action text NOT NULL,
  changed_by bigint REFERENCES my_schema.users (id),
  changed_at timestamptz DEFAULT now()
);

CREATE TYPE my_schema.user_status_type AS ENUM ('active', 'inactive', 'suspended');

CREATE TYPE other_schema.severity_level AS ENUM ('low', 'medium', 'high', 'critical');

CREATE DOMAIN my_schema.positive_int AS int 
  CHECK (value > 0);

CREATE DOMAIN other_schema.email_address AS text 
  CHECK (value ~* E'^[^@]+@[^@]+\\.[^@]+$');

CREATE TYPE my_schema.address_type AS (street text, city text, zip text);

ALTER TYPE my_schema.user_status_type ADD VALUE 'pending';

ALTER DOMAIN my_schema.positive_int SET NOT NULL;

INSERT INTO my_schema.users (
  username,
  email
) VALUES
  ('admin', 'admin@example.com');

INSERT INTO other_schema.audit_log (
  table_name,
  record_id,
  action,
  changed_by
) VALUES
  ('users', 1, 'INSERT', 1);

SELECT
  u.id,
  u.username,
  u.email,
  CAST(u.status AS my_schema.user_status_type),
  u.metadata::text,
  CAST(NULL AS my_schema.address_type)
FROM my_schema.users AS u
WHERE
  u.status = 'active'
ORDER BY
  u.created_at;

SELECT
  a.id,
  a.action,
  u.username
FROM other_schema.audit_log AS a
JOIN my_schema.users AS u ON u.id = a.changed_by;

UPDATE my_schema.users SET status = 'inactive' WHERE username = 'admin';

DELETE FROM other_schema.audit_log WHERE action = 'INSERT';

CREATE INDEX idx_users_email ON my_schema.users (email);

CREATE INDEX idx_audit_action ON other_schema.audit_log (action);

DROP SCHEMA IF EXISTS my_schema CASCADE;

COMMENT ON TABLE my_schema.users IS 'Main users table';

COMMENT ON COLUMN my_schema.users.email IS 'User email address';

COMMENT ON FUNCTION my_schema.get_user_by_id(bigint) IS 'Fetch user by primary key';

CREATE TRIGGER trg_audit_insert
  AFTER INSERT
  ON my_schema.users
  FOR EACH ROW
  EXECUTE PROCEDURE other_schema.log_change();

CREATE TRIGGER trg_audit_update
  AFTER UPDATE
  ON my_schema.users
  FOR EACH ROW
  EXECUTE PROCEDURE my_schema.on_user_update();

ALTER TABLE my_schema.users SET SCHEMA other_schema;

SELECT my_schema.get_user_by_id(1);

SELECT other_schema.compute_severity('high');

CREATE FUNCTION my_schema.kitchen_sink_fn(
  user_id bigint
) RETURNS my_schema.users AS $$DECLARE
  v_user my_schema.users;
  v_status my_schema.user_status_type;
  v_addr my_schema.address_type;
  v_severity other_schema.severity_level;
  v_audit_id bigint;
BEGIN
  SELECT * INTO v_user
      FROM my_schema.users
  WHERE
    id = user_id;
  v_status := v_user.status;
  INSERT INTO other_schema.audit_log (
    user_id
  ) VALUES
    (v_user.id) RETURNING id INTO v_audit_id;
  RETURN v_user;
END$$ LANGUAGE plpgsql STABLE;

CREATE FUNCTION other_schema.tg_audit_users() RETURNS trigger AS $$BEGIN
  IF tg_op = 'INSERT' THEN
      INSERT INTO other_schema.audit_log (
        user_id
      ) VALUES
        (new.id);
      RETURN NEW;
  END IF;
END$$ LANGUAGE plpgsql;

CREATE FUNCTION my_schema.cursor_edge_cases() RETURNS int AS $$DECLARE
  scan_cursor SCROLL CURSOR FOR SELECT id
  FROM my_schema.users
  ORDER BY
    id;
  ids int[] := ARRAY[0, 0, 0];
  current_id int;
BEGIN
  OPEN scan_cursor;
  MOVE FORWARD 2 FROM scan_cursor;
  FETCH PRIOR FROM scan_cursor INTO current_id;
  MOVE LAST FROM scan_cursor;
  CLOSE scan_cursor;
  ids[1] := current_id;
  RETURN (ids)[1];
EXCEPTION
  WHEN unique_violation OR SQLSTATE '23503' THEN
    RAISE;
END$$ LANGUAGE plpgsql;

CREATE VIEW my_schema.active_users AS SELECT
  id,
  username,
  email
FROM my_schema.users
WHERE
  status = 'active';

ALTER TABLE my_schema.users 
  ADD COLUMN bio text;

ALTER TABLE other_schema.audit_log 
  ADD COLUMN ip_address inet;

CREATE SEQUENCE my_schema.users_id_seq;

ALTER SEQUENCE my_schema.users_id_seq OWNED BY my_schema.users.id;

CREATE POLICY users_select_policy
  ON my_schema.users
  AS PERMISSIVE
  FOR SELECT
  TO PUBLIC
  USING (
    true
  );

CREATE POLICY audit_insert_policy
  ON other_schema.audit_log
  AS PERMISSIVE
  FOR INSERT
  TO PUBLIC
  WITH CHECK (
    true
  );

CREATE RULE notify_insert AS ON INSERT TO my_schema.users DO NOTHING;

CLUSTER my_schema.users USING idx_users_email;

VACUUM my_schema.users;

ANALYZE other_schema.audit_log;

SELECT assert_schema(CAST('my_schema' AS regnamespace));

SELECT assert_table(CAST('my_schema.users' AS regclass));

SELECT assert_function(CAST('my_schema.get_user_by_id(uuid)' AS regprocedure));

SELECT assert_trigger(CAST('my_schema.users' AS regclass), 'trg_audit_insert', CAST('my_schema.tg_audit' AS regproc), 5);

SELECT assert_type(CAST('my_schema.user_status_type' AS regtype));

SELECT assert_domain(CAST('my_schema.positive_int' AS regtype), CAST('int4' AS regtype));

SELECT '{"schema":"my_schema"}'::jsonb;

SELECT '{"source":"other_schema"}'::jsonb;

MERGE INTO my_schema.users AS u USING other_schema.audit_log AS s ON u.id = s.id WHEN MATCHED THEN UPDATE SET email = s.action WHEN NOT MATCHED THEN INSERT (id, email) VALUES (s.id, s.action);

SECURITY LABEL FOR anon ON COLUMN my_schema.users.email IS 'MASKED WITH FUNCTION anon.fake_email()';

GRANT SELECT ON ALL TABLES IN SCHEMA my_schema TO PUBLIC;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA other_schema FROM PUBLIC RESTRICT;

ALTER TABLE my_schema.users SET SCHEMA other_schema;

ALTER TYPE my_schema.user_status_type SET SCHEMA other_schema;

DO $$
BEGIN
  PERFORM "my_schema".get_user_by_id('00000000-0000-0000-0000-000000000000'::uuid);
END;
$$;

CREATE FUNCTION my_schema.cache_users() RETURNS void AS $$DECLARE
  cached my_schema.users[];
  current_user_row my_schema.users;
BEGIN
  SELECT * INTO current_user_row
      FROM my_schema.users
  LIMIT 1;
  cached := array_fill(current_user_row, ARRAY[1]);
END$$ LANGUAGE plpgsql;

COMMIT;