#!/usr/bin/env ts-node
import { ParseResult, RawStmt } from '@pgsql/types';
import * as fs from 'fs';
import { sync as globSync } from 'glob';
import { parse } from 'libpg-query';
import * as path from 'path';

const FIXTURE_DIR = path.join(__dirname, '../../../__fixtures__/kitchen-sink');
const OUT_DIR = path.join(__dirname, '../__tests__/kitchen-sink');
const MANIFEST_FILE = 'fixtures.json';

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

const generateTestFile = (versionPrevious: number, versionNext: number) => {
  return `// DO NOT EDIT BY HAND — generated by scripts/make-kitchen-sink.ts
import { readFileSync } from 'fs';
import { join } from 'path';

import { FixtureTestUtils } from '../../test-utils';

const manifest: Record<string, string[]> = JSON.parse(
  readFileSync(join(__dirname, '${MANIFEST_FILE}'), 'utf-8')
);
const fixtures = new FixtureTestUtils(${versionPrevious}, ${versionNext});

describe('${versionPrevious}-${versionNext}', () => {
  it.each(Object.entries(manifest))('%s', async (_name, tests) => {
    await fixtures.runFixtureTests(tests);
  });
});
`;
};

const fixtures = globSync(path.join(FIXTURE_DIR, '**/*.sql'));
const versions = [
  '13-14',
  '14-15',
  '15-16',
  '16-17',
  '17-18'
];

async function main() {
  const manifest: Record<string, string[]> = {};

  for (const fixturePath of fixtures) {
    const relPath = path.relative(FIXTURE_DIR, fixturePath);
    const sql = fs.readFileSync(fixturePath, 'utf-8');
    let statements: ParseResult;
    try {
      statements = await parse(sql);
    } catch (err: any) {
      console.error(`Failed to parse ${relPath}:`, err);
      continue;
    }

    const names = statements.stmts.map((stmt: RawStmt, idx: number) => {
      return `${relPath.replace(/\.sql$/, '')}-${idx + 1}.sql`;
    });

    if (names.length === 0) {
      // a fixture with no statements would generate a test that asserts nothing
      continue;
    }

    manifest[relPath.replace(/\//g, '-').replace(/\.sql$/, '')] = names;
  }

  ensureDir(OUT_DIR);
  // one manifest shared by every version pair, so the fixture list is written
  // once instead of once per (fixture file x version pair)
  fs.writeFileSync(path.join(OUT_DIR, MANIFEST_FILE), JSON.stringify(manifest, null, 2) + '\n');

  for (const version of versions) {
    const [versionPrevious, versionNext] = version.split('-').map(Number);
    fs.writeFileSync(
      path.join(OUT_DIR, `${version}.test.ts`),
      generateTestFile(versionPrevious, versionNext)
    );
  }
}

main().catch(console.error);
