/**
 * This file was automatically generated by pgsql-types.
 * DO NOT MODIFY IT BY HAND.
 * 
 * These types provide narrowed Node unions based on actual usage
 * patterns discovered by parsing SQL fixtures.
 */

import type { Node } from '@pgsql/types';
import { A_Expr_Kind, AggSplit, AlterPublicationAction, AlterSubscriptionType, AlterTSConfigType, AlterTableType, BoolExprType, BoolTestType, CTEMaterialize, CmdType, CoercionContext, CoercionForm, ConstrType, DefElemAction, DiscardMode, DropBehavior, FetchDirection, FunctionParameterMode, GrantTargetType, GroupingSetKind, ImportForeignSchemaType, JoinType, JsonBehaviorType, JsonConstructorType, JsonEncoding, JsonExprOp, JsonFormatType, JsonQuotes, JsonTableColumnType, JsonValueType, JsonWrapper, KeywordKind, LimitOption, LockClauseStrength, LockWaitPolicy, MergeMatchKind, MinMaxOp, NullTestType, ObjectType, OnCommitAction, OnConflictAction, OverridingKind, ParamKind, PartitionRangeDatumKind, PartitionStrategy, PublicationObjSpecType, QuerySource, RTEKind, ReindexObjectType, RoleSpecType, RoleStmtType, RowCompareType, SQLValueFunctionOp, SetOperation, SortByDir, SortByNulls, SubLinkType, TableFuncType, Token, TransactionStmtKind, VariableSetKind, ViewCheckOption, WCOKind, XmlExprOp, XmlOptionType } from '@pgsql/enums';
export type { Node } from '@pgsql/types';
export * from '@pgsql/enums';

// Narrowed type aliases for Node-typed fields
export type A_ArrayExpr_elements = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { CaseExpr: CaseExpr } | { CoalesceExpr: CoalesceExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { TypeCast: TypeCast };
export type A_Expr_lexpr = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { BoolExpr: BoolExpr } | { CaseExpr: CaseExpr } | { CoalesceExpr: CoalesceExpr } | { CollateClause: CollateClause } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { GroupingFunc: GroupingFunc } | { JsonFuncExpr: JsonFuncExpr } | { MinMaxExpr: MinMaxExpr } | { NullTest: NullTest } | { ParamRef: ParamRef } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { SubLink: SubLink } | { TypeCast: TypeCast } | { XmlSerialize: XmlSerialize };
export type A_Expr_name = { String: String };
export type A_Expr_rexpr = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { BoolExpr: BoolExpr } | { CaseExpr: CaseExpr } | { CoalesceExpr: CoalesceExpr } | { CollateClause: CollateClause } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { List: List } | { MergeSupportFunc: MergeSupportFunc } | { NullTest: NullTest } | { ParamRef: ParamRef } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { SubLink: SubLink } | { TypeCast: TypeCast } | { XmlSerialize: XmlSerialize };
export type A_Indices_lidx = { A_Const: A_Const };
export type A_Indices_uidx = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef };
export type A_Indirection_arg = { A_Indirection: A_Indirection } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { JsonFuncExpr: JsonFuncExpr } | { RowExpr: RowExpr } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type A_Indirection_indirection = { A_Indices: A_Indices } | { A_Star: A_Star } | { String: String };
export type AccessPriv_cols = { String: String };
export type AlterCollationStmt_collname = { String: String };
export type AlterDatabaseStmt_options = { DefElem: DefElem };
export type AlterDefaultPrivilegesStmt_options = { DefElem: DefElem };
export type AlterDomainStmt_def = { A_Const: A_Const } | { Constraint: Constraint };
export type AlterDomainStmt_typeName = { String: String };
export type AlterEnumStmt_typeName = { String: String };
export type AlterExtensionContentsStmt_object = { ObjectWithArgs: ObjectWithArgs };
export type AlterExtensionStmt_options = { DefElem: DefElem };
export type AlterFdwStmt_func_options = { DefElem: DefElem };
export type AlterFdwStmt_options = { DefElem: DefElem };
export type AlterForeignServerStmt_options = { DefElem: DefElem };
export type AlterFunctionStmt_actions = { DefElem: DefElem };
export type AlterObjectSchemaStmt_object = { List: List } | { ObjectWithArgs: ObjectWithArgs } | { String: String };
export type AlterOpFamilyStmt_items = { CreateOpClassItem: CreateOpClassItem };
export type AlterOpFamilyStmt_opfamilyname = { String: String };
export type AlterOperatorStmt_options = { DefElem: DefElem };
export type AlterOwnerStmt_object = { Integer: Integer } | { List: List } | { ObjectWithArgs: ObjectWithArgs } | { String: String };
export type AlterPolicyStmt_qual = { A_Const: A_Const } | { A_Expr: A_Expr } | { SubLink: SubLink };
export type AlterPolicyStmt_roles = { RoleSpec: RoleSpec };
export type AlterPolicyStmt_with_check = { SubLink: SubLink };
export type AlterPublicationStmt_options = { DefElem: DefElem };
export type AlterPublicationStmt_pubobjects = { PublicationObjSpec: PublicationObjSpec };
export type AlterRoleStmt_options = { DefElem: DefElem };
export type AlterSeqStmt_options = { DefElem: DefElem };
export type AlterStatsStmt_defnames = { String: String };
export type AlterStatsStmt_stxstattarget = { Integer: Integer };
export type AlterSubscriptionStmt_options = { DefElem: DefElem };
export type AlterSubscriptionStmt_publication = { String: String };
export type AlterTSConfigurationStmt_cfgname = { String: String };
export type AlterTSConfigurationStmt_dicts = { List: List };
export type AlterTSConfigurationStmt_tokentype = { String: String };
export type AlterTSDictionaryStmt_dictname = { String: String };
export type AlterTSDictionaryStmt_options = { DefElem: DefElem };
export type AlterTableCmd_def = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnDef: ColumnDef } | { Constraint: Constraint } | { FuncCall: FuncCall } | { Integer: Integer } | { List: List } | { PartitionCmd: PartitionCmd } | { RangeVar: RangeVar } | { ReplicaIdentityStmt: ReplicaIdentityStmt } | { String: String } | { TypeCast: TypeCast } | { TypeName: TypeName };
export type AlterTableSpaceOptionsStmt_options = { DefElem: DefElem };
export type AlterTableStmt_cmds = { AlterTableCmd: AlterTableCmd };
export type AlterTypeStmt_options = { DefElem: DefElem };
export type AlterTypeStmt_typeName = { String: String };
export type AlterUserMappingStmt_options = { DefElem: DefElem };
export type BoolExpr_args = { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { BooleanTest: BooleanTest } | { CaseExpr: CaseExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { JsonIsPredicate: JsonIsPredicate } | { NullTest: NullTest } | { ParamRef: ParamRef } | { SubLink: SubLink } | { TypeCast: TypeCast } | { XmlExpr: XmlExpr };
export type BooleanTest_arg = { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { ColumnRef: ColumnRef } | { TypeCast: TypeCast };
export type CaseExpr_arg = { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { CaseExpr: CaseExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { GroupingFunc: GroupingFunc } | { MergeSupportFunc: MergeSupportFunc } | { TypeCast: TypeCast };
export type CaseExpr_args = { CaseWhen: CaseWhen };
export type CaseExpr_defresult = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { CaseExpr: CaseExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type CaseWhen_expr = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { BooleanTest: BooleanTest } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { NullTest: NullTest } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type CaseWhen_result = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { CaseExpr: CaseExpr } | { CoalesceExpr: CoalesceExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type CoalesceExpr_args = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { RowExpr: RowExpr } | { TypeCast: TypeCast };
export type CollateClause_arg = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { CaseExpr: CaseExpr } | { ColumnRef: ColumnRef } | { TypeCast: TypeCast };
export type CollateClause_collname = { String: String };
export type ColumnDef_constraints = { Constraint: Constraint };
export type ColumnDef_fdwoptions = { DefElem: DefElem };
export type ColumnDef_raw_default = { A_Const: A_Const } | { A_Expr: A_Expr } | { CaseExpr: CaseExpr } | { FuncCall: FuncCall } | { TypeCast: TypeCast };
export type ColumnRef_fields = { A_Star: A_Star } | { String: String };
export type CommentStmt_object = { Integer: Integer } | { List: List } | { ObjectWithArgs: ObjectWithArgs } | { String: String } | { TypeName: TypeName };
export type CommonTableExpr_aliascolnames = { String: String };
export type CommonTableExpr_ctequery = { DeleteStmt: DeleteStmt } | { InsertStmt: InsertStmt } | { MergeStmt: MergeStmt } | { SelectStmt: SelectStmt } | { UpdateStmt: UpdateStmt };
export type CompositeTypeStmt_coldeflist = { ColumnDef: ColumnDef };
export type Constraint_exclusions = { List: List };
export type Constraint_fk_attrs = { String: String };
export type Constraint_fk_del_set_cols = { String: String };
export type Constraint_including = { String: String };
export type Constraint_keys = { String: String };
export type Constraint_options = { DefElem: DefElem };
export type Constraint_pk_attrs = { String: String };
export type Constraint_raw_expr = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { JsonFuncExpr: JsonFuncExpr } | { JsonIsPredicate: JsonIsPredicate } | { NullTest: NullTest } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type Constraint_where_clause = { A_Expr: A_Expr } | { NullTest: NullTest };
export type ConstraintsSetStmt_constraints = { RangeVar: RangeVar };
export type CopyStmt_attlist = { String: String };
export type CopyStmt_options = { DefElem: DefElem };
export type CopyStmt_query = { DeleteStmt: DeleteStmt } | { InsertStmt: InsertStmt } | { MergeStmt: MergeStmt } | { SelectStmt: SelectStmt } | { UpdateStmt: UpdateStmt };
export type CopyStmt_whereClause = { A_Expr: A_Expr } | { SubLink: SubLink };
export type CreateAmStmt_handler_name = { String: String };
export type CreateConversionStmt_conversion_name = { String: String };
export type CreateConversionStmt_func_name = { String: String };
export type CreateDomainStmt_constraints = { Constraint: Constraint };
export type CreateDomainStmt_domainname = { String: String };
export type CreateEnumStmt_typeName = { String: String };
export type CreateEnumStmt_vals = { String: String };
export type CreateEventTrigStmt_funcname = { String: String };
export type CreateEventTrigStmt_whenclause = { DefElem: DefElem };
export type CreateExtensionStmt_options = { DefElem: DefElem };
export type CreateFdwStmt_func_options = { DefElem: DefElem };
export type CreateFdwStmt_options = { DefElem: DefElem };
export type CreateForeignServerStmt_options = { DefElem: DefElem };
export type CreateForeignTableStmt_options = { DefElem: DefElem };
export type CreateFunctionStmt_funcname = { String: String };
export type CreateFunctionStmt_options = { DefElem: DefElem };
export type CreateFunctionStmt_parameters = { FunctionParameter: FunctionParameter };
export type CreateFunctionStmt_sql_body = { List: List } | { ReturnStmt: ReturnStmt };
export type CreateOpClassItem_class_args = { TypeName: TypeName };
export type CreateOpClassItem_order_family = { String: String };
export type CreateOpClassStmt_items = { CreateOpClassItem: CreateOpClassItem };
export type CreateOpClassStmt_opclassname = { String: String };
export type CreateOpFamilyStmt_opfamilyname = { String: String };
export type CreatePLangStmt_plhandler = { String: String };
export type CreatePolicyStmt_qual = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { CaseExpr: CaseExpr } | { FuncCall: FuncCall } | { SubLink: SubLink };
export type CreatePolicyStmt_roles = { RoleSpec: RoleSpec };
export type CreatePolicyStmt_with_check = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { SubLink: SubLink };
export type CreatePublicationStmt_options = { DefElem: DefElem };
export type CreatePublicationStmt_pubobjects = { PublicationObjSpec: PublicationObjSpec };
export type CreateRangeStmt_params = { DefElem: DefElem };
export type CreateRangeStmt_typeName = { String: String };
export type CreateRoleStmt_options = { DefElem: DefElem };
export type CreateSchemaStmt_schemaElts = { CreateSeqStmt: CreateSeqStmt } | { CreateStmt: CreateStmt } | { CreateTrigStmt: CreateTrigStmt } | { IndexStmt: IndexStmt } | { ViewStmt: ViewStmt };
export type CreateSeqStmt_options = { DefElem: DefElem };
export type CreateStatsStmt_defnames = { String: String };
export type CreateStatsStmt_exprs = { StatsElem: StatsElem };
export type CreateStatsStmt_relations = { RangeVar: RangeVar };
export type CreateStatsStmt_stat_types = { String: String };
export type CreateStmt_inhRelations = { RangeVar: RangeVar };
export type CreateStmt_options = { DefElem: DefElem };
export type CreateStmt_tableElts = { ColumnDef: ColumnDef } | { Constraint: Constraint } | { TableLikeClause: TableLikeClause };
export type CreateSubscriptionStmt_options = { DefElem: DefElem };
export type CreateSubscriptionStmt_publication = { String: String };
export type CreateTableAsStmt_query = { ExecuteStmt: ExecuteStmt } | { SelectStmt: SelectStmt };
export type CreateTableSpaceStmt_options = { DefElem: DefElem };
export type CreateTrigStmt_args = { String: String };
export type CreateTrigStmt_columns = { String: String };
export type CreateTrigStmt_funcname = { String: String };
export type CreateTrigStmt_transitionRels = { TriggerTransition: TriggerTransition };
export type CreateTrigStmt_whenClause = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { NullTest: NullTest };
export type CreateUserMappingStmt_options = { DefElem: DefElem };
export type CreatedbStmt_options = { DefElem: DefElem };
export type DeclareCursorStmt_query = { SelectStmt: SelectStmt };
export type DefElem_arg = { A_Const: A_Const } | { A_Star: A_Star } | { Boolean: Boolean } | { Float: Float } | { Integer: Integer } | { List: List } | { String: String } | { TypeName: TypeName } | { VariableSetStmt: VariableSetStmt };
export type DefineStmt_args = { Integer: Integer } | { List: List };
export type DefineStmt_definition = { DefElem: DefElem };
export type DefineStmt_defnames = { String: String };
export type DeleteStmt_returningList = { ResTarget: ResTarget };
export type DeleteStmt_usingClause = { JoinExpr: JoinExpr } | { RangeSubselect: RangeSubselect } | { RangeVar: RangeVar };
export type DeleteStmt_whereClause = { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { CurrentOfExpr: CurrentOfExpr } | { FuncCall: FuncCall } | { NullTest: NullTest } | { SubLink: SubLink };
export type DoStmt_args = { DefElem: DefElem };
export type DropOwnedStmt_roles = { RoleSpec: RoleSpec };
export type DropRoleStmt_roles = { RoleSpec: RoleSpec };
export type DropStmt_objects = { List: List } | { ObjectWithArgs: ObjectWithArgs } | { String: String } | { TypeName: TypeName };
export type DropdbStmt_options = { DefElem: DefElem };
export type ExecuteStmt_params = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { FuncCall: FuncCall } | { TypeCast: TypeCast };
export type ExplainStmt_options = { DefElem: DefElem };
export type ExplainStmt_query = { CreateTableAsStmt: CreateTableAsStmt } | { DeclareCursorStmt: DeclareCursorStmt } | { DeleteStmt: DeleteStmt } | { ExecuteStmt: ExecuteStmt } | { InsertStmt: InsertStmt } | { MergeStmt: MergeStmt } | { SelectStmt: SelectStmt } | { UpdateStmt: UpdateStmt };
export type FuncCall_agg_filter = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { NullTest: NullTest } | { SubLink: SubLink };
export type FuncCall_agg_order = { SortBy: SortBy };
export type FuncCall_args = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { BoolExpr: BoolExpr } | { CaseExpr: CaseExpr } | { CoalesceExpr: CoalesceExpr } | { CollateClause: CollateClause } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { JsonFuncExpr: JsonFuncExpr } | { JsonParseExpr: JsonParseExpr } | { JsonSerializeExpr: JsonSerializeExpr } | { MinMaxExpr: MinMaxExpr } | { NamedArgExpr: NamedArgExpr } | { ParamRef: ParamRef } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { SubLink: SubLink } | { TypeCast: TypeCast } | { XmlExpr: XmlExpr };
export type FuncCall_funcname = { String: String };
export type FunctionParameter_defexpr = { A_Const: A_Const } | { FuncCall: FuncCall } | { SQLValueFunction: SQLValueFunction } | { TypeCast: TypeCast };
export type GrantRoleStmt_granted_roles = { AccessPriv: AccessPriv };
export type GrantRoleStmt_grantee_roles = { RoleSpec: RoleSpec };
export type GrantRoleStmt_opt = { DefElem: DefElem };
export type GrantStmt_grantees = { RoleSpec: RoleSpec };
export type GrantStmt_objects = { Integer: Integer } | { List: List } | { ObjectWithArgs: ObjectWithArgs } | { RangeVar: RangeVar } | { String: String };
export type GrantStmt_privileges = { AccessPriv: AccessPriv };
export type GroupingFunc_args = { A_Expr: A_Expr } | { ColumnRef: ColumnRef };
export type GroupingSet_content = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef } | { GroupingSet: GroupingSet } | { RowExpr: RowExpr } | { TypeCast: TypeCast };
export type ImportForeignSchemaStmt_options = { DefElem: DefElem };
export type ImportForeignSchemaStmt_table_list = { RangeVar: RangeVar };
export type IndexElem_collation = { String: String };
export type IndexElem_expr = { A_Const: A_Const } | { A_Expr: A_Expr } | { CoalesceExpr: CoalesceExpr } | { CollateClause: CollateClause } | { FuncCall: FuncCall } | { JsonFuncExpr: JsonFuncExpr } | { RowExpr: RowExpr } | { TypeCast: TypeCast };
export type IndexElem_opclass = { String: String };
export type IndexElem_opclassopts = { DefElem: DefElem };
export type IndexStmt_indexIncludingParams = { IndexElem: IndexElem };
export type IndexStmt_indexParams = { IndexElem: IndexElem };
export type IndexStmt_options = { DefElem: DefElem };
export type IndexStmt_whereClause = { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { FuncCall: FuncCall } | { NullTest: NullTest };
export type InsertStmt_cols = { ResTarget: ResTarget };
export type InsertStmt_returningList = { ResTarget: ResTarget };
export type InsertStmt_selectStmt = { SelectStmt: SelectStmt };
export type JoinExpr_larg = { JoinExpr: JoinExpr } | { RangeFunction: RangeFunction } | { RangeSubselect: RangeSubselect } | { RangeVar: RangeVar };
export type JoinExpr_quals = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { NullTest: NullTest } | { SubLink: SubLink };
export type JoinExpr_rarg = { JoinExpr: JoinExpr } | { JsonTable: JsonTable } | { RangeFunction: RangeFunction } | { RangeSubselect: RangeSubselect } | { RangeVar: RangeVar };
export type JoinExpr_usingClause = { String: String };
export type JsonArrayConstructor_exprs = { JsonValueExpr: JsonValueExpr };
export type JsonArrayQueryConstructor_query = { SelectStmt: SelectStmt };
export type JsonFuncExpr_passing = { JsonArgument: JsonArgument };
export type JsonFuncExpr_pathspec = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef };
export type JsonIsPredicate_expr = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef } | { TypeCast: TypeCast };
export type JsonKeyValue_key = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { FuncCall: FuncCall } | { TypeCast: TypeCast };
export type JsonObjectConstructor_exprs = { JsonKeyValue: JsonKeyValue };
export type JsonScalarExpr_expr = { A_Const: A_Const } | { TypeCast: TypeCast };
export type JsonTable_columns = { JsonTableColumn: JsonTableColumn };
export type JsonTable_passing = { JsonArgument: JsonArgument };
export type JsonTableColumn_columns = { JsonTableColumn: JsonTableColumn };
export type JsonValueExpr_raw_expr = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef } | { JsonArrayConstructor: JsonArrayConstructor } | { TypeCast: TypeCast };
export type List_items = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { CoalesceExpr: CoalesceExpr } | { CollateClause: CollateClause } | { ColumnDef: ColumnDef } | { ColumnRef: ColumnRef } | { DefElem: DefElem } | { FuncCall: FuncCall } | { FunctionParameter: FunctionParameter } | { IndexElem: IndexElem } | { List: List } | { ParamRef: ParamRef } | { RoleSpec: RoleSpec } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { SetToDefault: SetToDefault } | { String: String } | { SubLink: SubLink } | { TypeCast: TypeCast } | { TypeName: TypeName };
export type LockStmt_relations = { RangeVar: RangeVar };
export type LockingClause_lockedRels = { RangeVar: RangeVar };
export type MergeStmt_joinCondition = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { SubLink: SubLink };
export type MergeStmt_mergeWhenClauses = { MergeWhenClause: MergeWhenClause };
export type MergeStmt_returningList = { ResTarget: ResTarget };
export type MergeStmt_sourceRelation = { JoinExpr: JoinExpr } | { RangeFunction: RangeFunction } | { RangeSubselect: RangeSubselect } | { RangeVar: RangeVar };
export type MergeWhenClause_condition = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { FuncCall: FuncCall } | { NullTest: NullTest } | { SubLink: SubLink };
export type MergeWhenClause_targetList = { ResTarget: ResTarget };
export type MergeWhenClause_values = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef } | { TypeCast: TypeCast };
export type MinMaxExpr_args = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef };
export type MultiAssignRef_source = { ColumnRef: ColumnRef } | { RowExpr: RowExpr } | { SubLink: SubLink };
export type NamedArgExpr_arg = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef } | { TypeCast: TypeCast };
export type NullTest_arg = { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { JsonArrayAgg: JsonArrayAgg } | { JsonObjectAgg: JsonObjectAgg } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { SubLink: SubLink };
export type ObjectWithArgs_objargs = { TypeName: TypeName };
export type ObjectWithArgs_objfuncargs = { FunctionParameter: FunctionParameter };
export type ObjectWithArgs_objname = { String: String };
export type PartitionElem_collation = { String: String };
export type PartitionElem_expr = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { RowExpr: RowExpr } | { TypeCast: TypeCast };
export type PartitionElem_opclass = { String: String };
export type PrepareStmt_argtypes = { TypeName: TypeName };
export type PrepareStmt_query = { InsertStmt: InsertStmt } | { MergeStmt: MergeStmt } | { SelectStmt: SelectStmt } | { UpdateStmt: UpdateStmt };
export type RangeFunction_coldeflist = { ColumnDef: ColumnDef };
export type RangeFunction_functions = { List: List };
export type RangeSubselect_subquery = { SelectStmt: SelectStmt };
export type RangeTableFunc_columns = { RangeTableFuncCol: RangeTableFuncCol };
export type RangeTableFunc_docexpr = { A_Const: A_Const } | { ColumnRef: ColumnRef };
export type RangeTableFunc_namespaces = { ResTarget: ResTarget };
export type RangeTableFunc_rowexpr = { A_Const: A_Const } | { A_Expr: A_Expr } | { RowExpr: RowExpr };
export type RangeTableFuncCol_coldefexpr = { A_Const: A_Const } | { A_Expr: A_Expr };
export type RangeTableFuncCol_colexpr = { A_Const: A_Const } | { A_Expr: A_Expr };
export type RangeTableSample_args = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef } | { TypeCast: TypeCast };
export type RangeTableSample_method = { String: String };
export type RangeTableSample_relation = { RangeVar: RangeVar };
export type RangeTableSample_repeatable = { A_Const: A_Const } | { A_Expr: A_Expr } | { ColumnRef: ColumnRef };
export type ReassignOwnedStmt_roles = { RoleSpec: RoleSpec };
export type ReindexStmt_params = { DefElem: DefElem };
export type RenameStmt_object = { List: List } | { ObjectWithArgs: ObjectWithArgs } | { String: String };
export type ResTarget_indirection = { A_Indices: A_Indices } | { String: String };
export type ResTarget_val = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { BoolExpr: BoolExpr } | { BooleanTest: BooleanTest } | { CaseExpr: CaseExpr } | { CoalesceExpr: CoalesceExpr } | { CollateClause: CollateClause } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { GroupingFunc: GroupingFunc } | { JsonArrayAgg: JsonArrayAgg } | { JsonArrayConstructor: JsonArrayConstructor } | { JsonArrayQueryConstructor: JsonArrayQueryConstructor } | { JsonFuncExpr: JsonFuncExpr } | { JsonIsPredicate: JsonIsPredicate } | { JsonObjectAgg: JsonObjectAgg } | { JsonObjectConstructor: JsonObjectConstructor } | { JsonParseExpr: JsonParseExpr } | { JsonScalarExpr: JsonScalarExpr } | { JsonSerializeExpr: JsonSerializeExpr } | { MergeSupportFunc: MergeSupportFunc } | { MinMaxExpr: MinMaxExpr } | { MultiAssignRef: MultiAssignRef } | { NullTest: NullTest } | { ParamRef: ParamRef } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { SetToDefault: SetToDefault } | { SubLink: SubLink } | { TypeCast: TypeCast } | { XmlExpr: XmlExpr } | { XmlSerialize: XmlSerialize };
export type ReturnStmt_returnval = { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { BoolExpr: BoolExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type RowExpr_args = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { CollateClause: CollateClause } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { RowExpr: RowExpr } | { SetToDefault: SetToDefault } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type RuleStmt_actions = { DeleteStmt: DeleteStmt } | { InsertStmt: InsertStmt } | { NotifyStmt: NotifyStmt } | { SelectStmt: SelectStmt } | { UpdateStmt: UpdateStmt };
export type RuleStmt_whereClause = { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { SubLink: SubLink };
export type SecLabelStmt_object = { List: List } | { String: String };
export type SelectStmt_distinctClause = { A_Const: A_Const } | { ColumnRef: ColumnRef };
export type SelectStmt_fromClause = { JoinExpr: JoinExpr } | { JsonTable: JsonTable } | { RangeFunction: RangeFunction } | { RangeSubselect: RangeSubselect } | { RangeTableFunc: RangeTableFunc } | { RangeTableSample: RangeTableSample } | { RangeVar: RangeVar };
export type SelectStmt_groupClause = { A_Const: A_Const } | { A_Expr: A_Expr } | { CollateClause: CollateClause } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { GroupingSet: GroupingSet } | { RowExpr: RowExpr } | { TypeCast: TypeCast };
export type SelectStmt_havingClause = { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { ColumnRef: ColumnRef } | { SubLink: SubLink };
export type SelectStmt_limitCount = { A_Const: A_Const } | { A_Expr: A_Expr } | { CaseExpr: CaseExpr } | { FuncCall: FuncCall };
export type SelectStmt_limitOffset = { A_Const: A_Const } | { A_Expr: A_Expr } | { CaseExpr: CaseExpr } | { ColumnRef: ColumnRef };
export type SelectStmt_lockingClause = { LockingClause: LockingClause };
export type SelectStmt_sortClause = { SortBy: SortBy };
export type SelectStmt_targetList = { ResTarget: ResTarget };
export type SelectStmt_valuesLists = { List: List };
export type SelectStmt_whereClause = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { BooleanTest: BooleanTest } | { CaseExpr: CaseExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { JsonIsPredicate: JsonIsPredicate } | { NullTest: NullTest } | { SubLink: SubLink };
export type SelectStmt_windowClause = { WindowDef: WindowDef };
export type SortBy_node = { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { CollateClause: CollateClause } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { RowExpr: RowExpr } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type SortBy_useOp = { String: String };
export type StatsElem_expr = { A_Expr: A_Expr } | { CaseExpr: CaseExpr } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall };
export type SubLink_operName = { String: String };
export type SubLink_subselect = { SelectStmt: SelectStmt };
export type SubLink_testexpr = { A_Const: A_Const } | { A_Expr: A_Expr } | { CaseExpr: CaseExpr } | { ColumnRef: ColumnRef } | { RowExpr: RowExpr } | { TypeCast: TypeCast };
export type TransactionStmt_options = { DefElem: DefElem };
export type TruncateStmt_relations = { RangeVar: RangeVar };
export type TypeCast_arg = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { A_Expr: A_Expr } | { A_Indirection: A_Indirection } | { CollateClause: CollateClause } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { ParamRef: ParamRef } | { RowExpr: RowExpr } | { SQLValueFunction: SQLValueFunction } | { SubLink: SubLink } | { TypeCast: TypeCast };
export type TypeName_arrayBounds = { Integer: Integer };
export type TypeName_names = { String: String };
export type TypeName_typmods = { A_Const: A_Const } | { ColumnRef: ColumnRef };
export type UpdateStmt_fromClause = { JoinExpr: JoinExpr } | { RangeFunction: RangeFunction } | { RangeSubselect: RangeSubselect } | { RangeVar: RangeVar };
export type UpdateStmt_returningList = { ResTarget: ResTarget };
export type UpdateStmt_targetList = { ResTarget: ResTarget };
export type UpdateStmt_whereClause = { A_Const: A_Const } | { A_Expr: A_Expr } | { BoolExpr: BoolExpr } | { ColumnRef: ColumnRef } | { CurrentOfExpr: CurrentOfExpr } | { FuncCall: FuncCall } | { NullTest: NullTest } | { SubLink: SubLink };
export type VacuumRelation_va_cols = { String: String };
export type VacuumStmt_options = { DefElem: DefElem };
export type VacuumStmt_rels = { VacuumRelation: VacuumRelation };
export type VariableSetStmt_args = { A_Const: A_Const } | { DefElem: DefElem };
export type ViewStmt_aliases = { String: String };
export type ViewStmt_options = { DefElem: DefElem };
export type ViewStmt_query = { SelectStmt: SelectStmt };
export type WindowDef_endOffset = { A_Const: A_Const } | { TypeCast: TypeCast };
export type WindowDef_orderClause = { SortBy: SortBy };
export type WindowDef_partitionClause = { ColumnRef: ColumnRef };
export type WindowDef_startOffset = { A_Const: A_Const } | { TypeCast: TypeCast };
export type XmlExpr_args = { A_ArrayExpr: A_ArrayExpr } | { A_Const: A_Const } | { ColumnRef: ColumnRef } | { FuncCall: FuncCall } | { ParamRef: ParamRef } | { TypeCast: TypeCast } | { XmlExpr: XmlExpr };
export type XmlExpr_named_args = { ResTarget: ResTarget };
export type XmlSerialize_expr = { A_Const: A_Const } | { ColumnRef: ColumnRef };

// Interfaces with narrowed Node types
export interface A_ArrayExpr {
  elements?: A_ArrayExpr_elements[];
  location?: number;
}

export interface A_Const {
  boolval?: { Boolean: Boolean };
  bsval?: { BitString: BitString };
  fval?: { Float: Float };
  isnull?: boolean;
  ival?: { Integer: Integer };
  location?: number;
  sval?: { String: String };
}

export interface A_Expr {
  kind?: A_Expr_Kind;
  lexpr?: A_Expr_lexpr;
  location?: number;
  name?: A_Expr_name[];
  rexpr?: A_Expr_rexpr;
}

export interface A_Indices {
  is_slice?: boolean;
  lidx?: A_Indices_lidx;
  uidx?: A_Indices_uidx;
}

export interface A_Indirection {
  arg?: A_Indirection_arg;
  indirection?: A_Indirection_indirection[];
}

export interface A_Star {
}

export interface AccessPriv {
  cols?: AccessPriv_cols[];
  priv_name?: string;
}

export interface Aggref {
  aggargtypes?: Node[];
  aggcollid?: number;
  aggdirectargs?: Node[];
  aggdistinct?: Node[];
  aggfilter?: Node;
  aggfnoid?: number;
  aggkind?: string;
  agglevelsup?: number;
  aggno?: number;
  aggorder?: Node[];
  aggsplit?: AggSplit;
  aggstar?: boolean;
  aggtransno?: number;
  aggtype?: number;
  aggvariadic?: boolean;
  args?: Node[];
  inputcollid?: number;
  location?: number;
  xpr?: Node;
}

export interface Alias {
  aliasname?: string;
  colnames?: Node[];
}

export interface AlterCollationStmt {
  collname?: AlterCollationStmt_collname[];
}

export interface AlterDatabaseRefreshCollStmt {
  dbname?: string;
}

export interface AlterDatabaseSetStmt {
  dbname?: string;
  setstmt?: { VariableSetStmt: VariableSetStmt };
}

export interface AlterDatabaseStmt {
  dbname?: string;
  options?: AlterDatabaseStmt_options[];
}

export interface AlterDefaultPrivilegesStmt {
  action?: { GrantStmt: GrantStmt };
  options?: AlterDefaultPrivilegesStmt_options[];
}

export interface AlterDomainStmt {
  behavior?: DropBehavior;
  def?: AlterDomainStmt_def;
  missing_ok?: boolean;
  name?: string;
  subtype?: string;
  typeName?: AlterDomainStmt_typeName[];
}

export interface AlterEnumStmt {
  newVal?: string;
  newValIsAfter?: boolean;
  newValNeighbor?: string;
  oldVal?: string;
  skipIfNewValExists?: boolean;
  typeName?: AlterEnumStmt_typeName[];
}

export interface AlterEventTrigStmt {
  tgenabled?: string;
  trigname?: string;
}

export interface AlterExtensionContentsStmt {
  action?: number;
  extname?: string;
  object?: AlterExtensionContentsStmt_object;
  objtype?: ObjectType;
}

export interface AlterExtensionStmt {
  extname?: string;
  options?: AlterExtensionStmt_options[];
}

export interface AlterFdwStmt {
  fdwname?: string;
  func_options?: AlterFdwStmt_func_options[];
  options?: AlterFdwStmt_options[];
}

export interface AlterForeignServerStmt {
  has_version?: boolean;
  options?: AlterForeignServerStmt_options[];
  servername?: string;
  version?: string;
}

export interface AlterFunctionStmt {
  actions?: AlterFunctionStmt_actions[];
  func?: { ObjectWithArgs: ObjectWithArgs };
  objtype?: ObjectType;
}

export interface AlternativeSubPlan {
  subplans?: Node[];
  xpr?: Node;
}

export interface AlterObjectDependsStmt {
  extname?: { String: String };
  object?: Node;
  objectType?: ObjectType;
  relation?: { RangeVar: RangeVar };
  remove?: boolean;
}

export interface AlterObjectSchemaStmt {
  missing_ok?: boolean;
  newschema?: string;
  object?: AlterObjectSchemaStmt_object;
  objectType?: ObjectType;
  relation?: { RangeVar: RangeVar };
}

export interface AlterOperatorStmt {
  opername?: { ObjectWithArgs: ObjectWithArgs };
  options?: AlterOperatorStmt_options[];
}

export interface AlterOpFamilyStmt {
  amname?: string;
  isDrop?: boolean;
  items?: AlterOpFamilyStmt_items[];
  opfamilyname?: AlterOpFamilyStmt_opfamilyname[];
}

export interface AlterOwnerStmt {
  newowner?: { RoleSpec: RoleSpec };
  object?: AlterOwnerStmt_object;
  objectType?: ObjectType;
  relation?: { RangeVar: RangeVar };
}

export interface AlterPolicyStmt {
  policy_name?: string;
  qual?: AlterPolicyStmt_qual;
  roles?: AlterPolicyStmt_roles[];
  table?: { RangeVar: RangeVar };
  with_check?: AlterPolicyStmt_with_check;
}

export interface AlterPublicationStmt {
  action?: AlterPublicationAction;
  for_all_tables?: boolean;
  options?: AlterPublicationStmt_options[];
  pubname?: string;
  pubobjects?: AlterPublicationStmt_pubobjects[];
}

export interface AlterRoleSetStmt {
  database?: string;
  role?: { RoleSpec: RoleSpec };
  setstmt?: { VariableSetStmt: VariableSetStmt };
}

export interface AlterRoleStmt {
  action?: number;
  options?: AlterRoleStmt_options[];
  role?: { RoleSpec: RoleSpec };
}

export interface AlterSeqStmt {
  for_identity?: boolean;
  missing_ok?: boolean;
  options?: AlterSeqStmt_options[];
  sequence?: { RangeVar: RangeVar };
}

export interface AlterStatsStmt {
  defnames?: AlterStatsStmt_defnames[];
  missing_ok?: boolean;
  stxstattarget?: AlterStatsStmt_stxstattarget;
}

export interface AlterSubscriptionStmt {
  conninfo?: string;
  kind?: AlterSubscriptionType;
  options?: AlterSubscriptionStmt_options[];
  publication?: AlterSubscriptionStmt_publication[];
  subname?: string;
}

export interface AlterSystemStmt {
  setstmt?: { VariableSetStmt: VariableSetStmt };
}

export interface AlterTableCmd {
  behavior?: DropBehavior;
  def?: AlterTableCmd_def;
  missing_ok?: boolean;
  name?: string;
  newowner?: { RoleSpec: RoleSpec };
  num?: number;
  recurse?: boolean;
  subtype?: AlterTableType;
}

export interface AlterTableMoveAllStmt {
  new_tablespacename?: string;
  nowait?: boolean;
  objtype?: ObjectType;
  orig_tablespacename?: string;
  roles?: Node[];
}

export interface AlterTableSpaceOptionsStmt {
  isReset?: boolean;
  options?: AlterTableSpaceOptionsStmt_options[];
  tablespacename?: string;
}

export interface AlterTableStmt {
  cmds?: AlterTableStmt_cmds[];
  missing_ok?: boolean;
  objtype?: ObjectType;
  relation?: { RangeVar: RangeVar };
}

export interface AlterTSConfigurationStmt {
  cfgname?: AlterTSConfigurationStmt_cfgname[];
  dicts?: AlterTSConfigurationStmt_dicts[];
  kind?: AlterTSConfigType;
  missing_ok?: boolean;
  override?: boolean;
  replace?: boolean;
  tokentype?: AlterTSConfigurationStmt_tokentype[];
}

export interface AlterTSDictionaryStmt {
  dictname?: AlterTSDictionaryStmt_dictname[];
  options?: AlterTSDictionaryStmt_options[];
}

export interface AlterTypeStmt {
  options?: AlterTypeStmt_options[];
  typeName?: AlterTypeStmt_typeName[];
}

export interface AlterUserMappingStmt {
  options?: AlterUserMappingStmt_options[];
  servername?: string;
  user?: { RoleSpec: RoleSpec };
}

export interface ArrayCoerceExpr {
  arg?: Node;
  coerceformat?: CoercionForm;
  elemexpr?: Node;
  location?: number;
  resultcollid?: number;
  resulttype?: number;
  resulttypmod?: number;
  xpr?: Node;
}

export interface ArrayExpr {
  array_collid?: number;
  array_typeid?: number;
  element_typeid?: number;
  elements?: Node[];
  location?: number;
  multidims?: boolean;
  xpr?: Node;
}

export interface BitString {
  bsval?: string;
}

export interface Boolean {
  boolval?: boolean;
}

export interface BooleanTest {
  arg?: BooleanTest_arg;
  booltesttype?: BoolTestType;
  location?: number;
  xpr?: Node;
}

export interface BoolExpr {
  args?: BoolExpr_args[];
  boolop?: BoolExprType;
  location?: number;
  xpr?: Node;
}

export interface CallContext {
  atomic?: boolean;
}

export interface CallStmt {
  funccall?: { FuncCall: FuncCall };
  funcexpr?: { FuncExpr: FuncExpr };
  outargs?: Node[];
}

export interface CaseExpr {
  arg?: CaseExpr_arg;
  args?: CaseExpr_args[];
  casecollid?: number;
  casetype?: number;
  defresult?: CaseExpr_defresult;
  location?: number;
  xpr?: Node;
}

export interface CaseTestExpr {
  collation?: number;
  typeId?: number;
  typeMod?: number;
  xpr?: Node;
}

export interface CaseWhen {
  expr?: CaseWhen_expr;
  location?: number;
  result?: CaseWhen_result;
  xpr?: Node;
}

export interface CheckPointStmt {
}

export interface ClosePortalStmt {
  portalname?: string;
}

export interface ClusterStmt {
  indexname?: string;
  params?: Node[];
  relation?: { RangeVar: RangeVar };
}

export interface CoalesceExpr {
  args?: CoalesceExpr_args[];
  coalescecollid?: number;
  coalescetype?: number;
  location?: number;
  xpr?: Node;
}

export interface CoerceToDomain {
  arg?: Node;
  coercionformat?: CoercionForm;
  location?: number;
  resultcollid?: number;
  resulttype?: number;
  resulttypmod?: number;
  xpr?: Node;
}

export interface CoerceToDomainValue {
  collation?: number;
  location?: number;
  typeId?: number;
  typeMod?: number;
  xpr?: Node;
}

export interface CoerceViaIO {
  arg?: Node;
  coerceformat?: CoercionForm;
  location?: number;
  resultcollid?: number;
  resulttype?: number;
  xpr?: Node;
}

export interface CollateClause {
  arg?: CollateClause_arg;
  collname?: CollateClause_collname[];
  location?: number;
}

export interface CollateExpr {
  arg?: Node;
  collOid?: number;
  location?: number;
  xpr?: Node;
}

export interface ColumnDef {
  collClause?: { CollateClause: CollateClause };
  collOid?: number;
  colname?: string;
  compression?: string;
  constraints?: ColumnDef_constraints[];
  cooked_default?: Node;
  fdwoptions?: ColumnDef_fdwoptions[];
  generated?: string;
  identity?: string;
  identitySequence?: { RangeVar: RangeVar };
  inhcount?: number;
  is_from_type?: boolean;
  is_local?: boolean;
  is_not_null?: boolean;
  location?: number;
  raw_default?: ColumnDef_raw_default;
  storage?: string;
  storage_name?: string;
  typeName?: { TypeName: TypeName };
}

export interface ColumnRef {
  fields?: ColumnRef_fields[];
  location?: number;
}

export interface CommentStmt {
  comment?: string;
  object?: CommentStmt_object;
  objtype?: ObjectType;
}

export interface CommonTableExpr {
  aliascolnames?: CommonTableExpr_aliascolnames[];
  ctecolcollations?: Node[];
  ctecolnames?: Node[];
  ctecoltypes?: Node[];
  ctecoltypmods?: Node[];
  ctematerialized?: CTEMaterialize;
  ctename?: string;
  ctequery?: CommonTableExpr_ctequery;
  cterecursive?: boolean;
  cterefcount?: number;
  cycle_clause?: { CTECycleClause: CTECycleClause };
  location?: number;
  search_clause?: { CTESearchClause: CTESearchClause };
}

export interface CompositeTypeStmt {
  coldeflist?: CompositeTypeStmt_coldeflist[];
  typevar?: { RangeVar: RangeVar };
}

export interface Constraint {
  access_method?: string;
  conname?: string;
  contype?: ConstrType;
  cooked_expr?: string;
  deferrable?: boolean;
  exclusions?: Constraint_exclusions[];
  fk_attrs?: Constraint_fk_attrs[];
  fk_del_action?: string;
  fk_del_set_cols?: Constraint_fk_del_set_cols[];
  fk_matchtype?: string;
  fk_upd_action?: string;
  generated_when?: string;
  including?: Constraint_including[];
  indexname?: string;
  indexspace?: string;
  inhcount?: number;
  initdeferred?: boolean;
  initially_valid?: boolean;
  is_no_inherit?: boolean;
  keys?: Constraint_keys[];
  location?: number;
  nulls_not_distinct?: boolean;
  old_conpfeqop?: Node[];
  old_pktable_oid?: number;
  options?: Constraint_options[];
  pk_attrs?: Constraint_pk_attrs[];
  pktable?: { RangeVar: RangeVar };
  raw_expr?: Constraint_raw_expr;
  reset_default_tblspc?: boolean;
  skip_validation?: boolean;
  where_clause?: Constraint_where_clause;
}

export interface ConstraintsSetStmt {
  constraints?: ConstraintsSetStmt_constraints[];
  deferred?: boolean;
}

export interface ConvertRowtypeExpr {
  arg?: Node;
  convertformat?: CoercionForm;
  location?: number;
  resulttype?: number;
  xpr?: Node;
}

export interface CopyStmt {
  attlist?: CopyStmt_attlist[];
  filename?: string;
  is_from?: boolean;
  is_program?: boolean;
  options?: CopyStmt_options[];
  query?: CopyStmt_query;
  relation?: { RangeVar: RangeVar };
  whereClause?: CopyStmt_whereClause;
}

export interface CreateAmStmt {
  amname?: string;
  amtype?: string;
  handler_name?: CreateAmStmt_handler_name[];
}

export interface CreateCastStmt {
  context?: CoercionContext;
  func?: { ObjectWithArgs: ObjectWithArgs };
  inout?: boolean;
  sourcetype?: { TypeName: TypeName };
  targettype?: { TypeName: TypeName };
}

export interface CreateConversionStmt {
  conversion_name?: CreateConversionStmt_conversion_name[];
  def?: boolean;
  for_encoding_name?: string;
  func_name?: CreateConversionStmt_func_name[];
  to_encoding_name?: string;
}

export interface CreatedbStmt {
  dbname?: string;
  options?: CreatedbStmt_options[];
}

export interface CreateDomainStmt {
  collClause?: { CollateClause: CollateClause };
  constraints?: CreateDomainStmt_constraints[];
  domainname?: CreateDomainStmt_domainname[];
  typeName?: { TypeName: TypeName };
}

export interface CreateEnumStmt {
  typeName?: CreateEnumStmt_typeName[];
  vals?: CreateEnumStmt_vals[];
}

export interface CreateEventTrigStmt {
  eventname?: string;
  funcname?: CreateEventTrigStmt_funcname[];
  trigname?: string;
  whenclause?: CreateEventTrigStmt_whenclause[];
}

export interface CreateExtensionStmt {
  extname?: string;
  if_not_exists?: boolean;
  options?: CreateExtensionStmt_options[];
}

export interface CreateFdwStmt {
  fdwname?: string;
  func_options?: CreateFdwStmt_func_options[];
  options?: CreateFdwStmt_options[];
}

export interface CreateForeignServerStmt {
  fdwname?: string;
  if_not_exists?: boolean;
  options?: CreateForeignServerStmt_options[];
  servername?: string;
  servertype?: string;
  version?: string;
}

export interface CreateForeignTableStmt {
  base?: { CreateStmt: CreateStmt };
  options?: CreateForeignTableStmt_options[];
  servername?: string;
}

export interface CreateFunctionStmt {
  funcname?: CreateFunctionStmt_funcname[];
  is_procedure?: boolean;
  options?: CreateFunctionStmt_options[];
  parameters?: CreateFunctionStmt_parameters[];
  replace?: boolean;
  returnType?: { TypeName: TypeName };
  sql_body?: CreateFunctionStmt_sql_body;
}

export interface CreateOpClassItem {
  class_args?: CreateOpClassItem_class_args[];
  itemtype?: number;
  name?: { ObjectWithArgs: ObjectWithArgs };
  number?: number;
  order_family?: CreateOpClassItem_order_family[];
  storedtype?: { TypeName: TypeName };
}

export interface CreateOpClassStmt {
  amname?: string;
  datatype?: { TypeName: TypeName };
  isDefault?: boolean;
  items?: CreateOpClassStmt_items[];
  opclassname?: CreateOpClassStmt_opclassname[];
  opfamilyname?: Node[];
}

export interface CreateOpFamilyStmt {
  amname?: string;
  opfamilyname?: CreateOpFamilyStmt_opfamilyname[];
}

export interface CreatePLangStmt {
  plhandler?: CreatePLangStmt_plhandler[];
  plinline?: Node[];
  plname?: string;
  pltrusted?: boolean;
  plvalidator?: Node[];
  replace?: boolean;
}

export interface CreatePolicyStmt {
  cmd_name?: string;
  permissive?: boolean;
  policy_name?: string;
  qual?: CreatePolicyStmt_qual;
  roles?: CreatePolicyStmt_roles[];
  table?: { RangeVar: RangeVar };
  with_check?: CreatePolicyStmt_with_check;
}

export interface CreatePublicationStmt {
  for_all_tables?: boolean;
  options?: CreatePublicationStmt_options[];
  pubname?: string;
  pubobjects?: CreatePublicationStmt_pubobjects[];
}

export interface CreateRangeStmt {
  params?: CreateRangeStmt_params[];
  typeName?: CreateRangeStmt_typeName[];
}

export interface CreateRoleStmt {
  options?: CreateRoleStmt_options[];
  role?: string;
  stmt_type?: RoleStmtType;
}

export interface CreateSchemaStmt {
  authrole?: { RoleSpec: RoleSpec };
  if_not_exists?: boolean;
  schemaElts?: CreateSchemaStmt_schemaElts[];
  schemaname?: string;
}

export interface CreateSeqStmt {
  for_identity?: boolean;
  if_not_exists?: boolean;
  options?: CreateSeqStmt_options[];
  ownerId?: number;
  sequence?: { RangeVar: RangeVar };
}

export interface CreateStatsStmt {
  defnames?: CreateStatsStmt_defnames[];
  exprs?: CreateStatsStmt_exprs[];
  if_not_exists?: boolean;
  relations?: CreateStatsStmt_relations[];
  stat_types?: CreateStatsStmt_stat_types[];
  stxcomment?: string;
  transformed?: boolean;
}

export interface CreateStmt {
  accessMethod?: string;
  constraints?: Node[];
  if_not_exists?: boolean;
  inhRelations?: CreateStmt_inhRelations[];
  ofTypename?: { TypeName: TypeName };
  oncommit?: OnCommitAction;
  options?: CreateStmt_options[];
  partbound?: { PartitionBoundSpec: PartitionBoundSpec };
  partspec?: { PartitionSpec: PartitionSpec };
  relation?: { RangeVar: RangeVar };
  tableElts?: CreateStmt_tableElts[];
  tablespacename?: string;
}

export interface CreateSubscriptionStmt {
  conninfo?: string;
  options?: CreateSubscriptionStmt_options[];
  publication?: CreateSubscriptionStmt_publication[];
  subname?: string;
}

export interface CreateTableAsStmt {
  if_not_exists?: boolean;
  into?: { IntoClause: IntoClause };
  is_select_into?: boolean;
  objtype?: ObjectType;
  query?: CreateTableAsStmt_query;
}

export interface CreateTableSpaceStmt {
  location?: string;
  options?: CreateTableSpaceStmt_options[];
  owner?: { RoleSpec: RoleSpec };
  tablespacename?: string;
}

export interface CreateTransformStmt {
  fromsql?: { ObjectWithArgs: ObjectWithArgs };
  lang?: string;
  replace?: boolean;
  tosql?: { ObjectWithArgs: ObjectWithArgs };
  type_name?: { TypeName: TypeName };
}

export interface CreateTrigStmt {
  args?: CreateTrigStmt_args[];
  columns?: CreateTrigStmt_columns[];
  constrrel?: { RangeVar: RangeVar };
  deferrable?: boolean;
  events?: number;
  funcname?: CreateTrigStmt_funcname[];
  initdeferred?: boolean;
  isconstraint?: boolean;
  relation?: { RangeVar: RangeVar };
  replace?: boolean;
  row?: boolean;
  timing?: number;
  transitionRels?: CreateTrigStmt_transitionRels[];
  trigname?: string;
  whenClause?: CreateTrigStmt_whenClause;
}

export interface CreateUserMappingStmt {
  if_not_exists?: boolean;
  options?: CreateUserMappingStmt_options[];
  servername?: string;
  user?: { RoleSpec: RoleSpec };
}

export interface CTECycleClause {
  cycle_col_list?: Node[];
  cycle_mark_collation?: number;
  cycle_mark_column?: string;
  cycle_mark_default?: Node;
  cycle_mark_neop?: number;
  cycle_mark_type?: number;
  cycle_mark_typmod?: number;
  cycle_mark_value?: Node;
  cycle_path_column?: string;
  location?: number;
}

export interface CTESearchClause {
  location?: number;
  search_breadth_first?: boolean;
  search_col_list?: Node[];
  search_seq_column?: string;
}

export interface CurrentOfExpr {
  cursor_name?: string;
  cursor_param?: number;
  cvarno?: number;
  xpr?: Node;
}

export interface DeallocateStmt {
  isall?: boolean;
  location?: number;
  name?: string;
}

export interface DeclareCursorStmt {
  options?: number;
  portalname?: string;
  query?: DeclareCursorStmt_query;
}

export interface DefElem {
  arg?: DefElem_arg;
  defaction?: DefElemAction;
  defname?: string;
  defnamespace?: string;
  location?: number;
}

export interface DefineStmt {
  args?: DefineStmt_args[];
  definition?: DefineStmt_definition[];
  defnames?: DefineStmt_defnames[];
  if_not_exists?: boolean;
  kind?: ObjectType;
  oldstyle?: boolean;
  replace?: boolean;
}

export interface DeleteStmt {
  relation?: { RangeVar: RangeVar };
  returningList?: DeleteStmt_returningList[];
  usingClause?: DeleteStmt_usingClause[];
  whereClause?: DeleteStmt_whereClause;
  withClause?: { WithClause: WithClause };
}

export interface DiscardStmt {
  target?: DiscardMode;
}

export interface DistinctExpr {
  args?: Node[];
  inputcollid?: number;
  location?: number;
  opcollid?: number;
  opno?: number;
  opresulttype?: number;
  opretset?: boolean;
  xpr?: Node;
}

export interface DoStmt {
  args?: DoStmt_args[];
}

export interface DropdbStmt {
  dbname?: string;
  missing_ok?: boolean;
  options?: DropdbStmt_options[];
}

export interface DropOwnedStmt {
  behavior?: DropBehavior;
  roles?: DropOwnedStmt_roles[];
}

export interface DropRoleStmt {
  missing_ok?: boolean;
  roles?: DropRoleStmt_roles[];
}

export interface DropStmt {
  behavior?: DropBehavior;
  concurrent?: boolean;
  missing_ok?: boolean;
  objects?: DropStmt_objects[];
  removeType?: ObjectType;
}

export interface DropSubscriptionStmt {
  behavior?: DropBehavior;
  missing_ok?: boolean;
  subname?: string;
}

export interface DropTableSpaceStmt {
  missing_ok?: boolean;
  tablespacename?: string;
}

export interface DropUserMappingStmt {
  missing_ok?: boolean;
  servername?: string;
  user?: { RoleSpec: RoleSpec };
}

export interface ExecuteStmt {
  name?: string;
  params?: ExecuteStmt_params[];
}

export interface ExplainStmt {
  options?: ExplainStmt_options[];
  query?: ExplainStmt_query;
}

export interface FetchStmt {
  direction?: FetchDirection;
  howMany?: number;
  ismove?: boolean;
  portalname?: string;
}

export interface FieldSelect {
  arg?: Node;
  fieldnum?: number;
  resultcollid?: number;
  resulttype?: number;
  resulttypmod?: number;
  xpr?: Node;
}

export interface FieldStore {
  arg?: Node;
  fieldnums?: Node[];
  newvals?: Node[];
  resulttype?: number;
  xpr?: Node;
}

export interface Float {
  fval?: string;
}

export interface FromExpr {
  fromlist?: Node[];
  quals?: Node;
}

export interface FuncCall {
  agg_distinct?: boolean;
  agg_filter?: FuncCall_agg_filter;
  agg_order?: FuncCall_agg_order[];
  agg_star?: boolean;
  agg_within_group?: boolean;
  args?: FuncCall_args[];
  func_variadic?: boolean;
  funcformat?: CoercionForm;
  funcname?: FuncCall_funcname[];
  location?: number;
  over?: { WindowDef: WindowDef };
}

export interface FuncExpr {
  args?: Node[];
  funccollid?: number;
  funcformat?: CoercionForm;
  funcid?: number;
  funcresulttype?: number;
  funcretset?: boolean;
  funcvariadic?: boolean;
  inputcollid?: number;
  location?: number;
  xpr?: Node;
}

export interface FunctionParameter {
  argType?: { TypeName: TypeName };
  defexpr?: FunctionParameter_defexpr;
  mode?: FunctionParameterMode;
  name?: string;
}

export interface GrantRoleStmt {
  behavior?: DropBehavior;
  granted_roles?: GrantRoleStmt_granted_roles[];
  grantee_roles?: GrantRoleStmt_grantee_roles[];
  grantor?: { RoleSpec: RoleSpec };
  is_grant?: boolean;
  opt?: GrantRoleStmt_opt[];
}

export interface GrantStmt {
  behavior?: DropBehavior;
  grant_option?: boolean;
  grantees?: GrantStmt_grantees[];
  grantor?: { RoleSpec: RoleSpec };
  is_grant?: boolean;
  objects?: GrantStmt_objects[];
  objtype?: ObjectType;
  privileges?: GrantStmt_privileges[];
  targtype?: GrantTargetType;
}

export interface GroupingFunc {
  agglevelsup?: number;
  args?: GroupingFunc_args[];
  location?: number;
  refs?: Node[];
  xpr?: Node;
}

export interface GroupingSet {
  content?: GroupingSet_content[];
  kind?: GroupingSetKind;
  location?: number;
}

export interface ImportForeignSchemaStmt {
  list_type?: ImportForeignSchemaType;
  local_schema?: string;
  options?: ImportForeignSchemaStmt_options[];
  remote_schema?: string;
  server_name?: string;
  table_list?: ImportForeignSchemaStmt_table_list[];
}

export interface IndexElem {
  collation?: IndexElem_collation[];
  expr?: IndexElem_expr;
  indexcolname?: string;
  name?: string;
  nulls_ordering?: SortByNulls;
  opclass?: IndexElem_opclass[];
  opclassopts?: IndexElem_opclassopts[];
  ordering?: SortByDir;
}

export interface IndexStmt {
  accessMethod?: string;
  concurrent?: boolean;
  deferrable?: boolean;
  excludeOpNames?: Node[];
  idxcomment?: string;
  idxname?: string;
  if_not_exists?: boolean;
  indexIncludingParams?: IndexStmt_indexIncludingParams[];
  indexOid?: number;
  indexParams?: IndexStmt_indexParams[];
  initdeferred?: boolean;
  isconstraint?: boolean;
  nulls_not_distinct?: boolean;
  oldCreateSubid?: number;
  oldFirstRelfilelocatorSubid?: number;
  oldNumber?: number;
  options?: IndexStmt_options[];
  primary?: boolean;
  relation?: { RangeVar: RangeVar };
  reset_default_tblspc?: boolean;
  tableSpace?: string;
  transformed?: boolean;
  unique?: boolean;
  whereClause?: IndexStmt_whereClause;
}

export interface InferClause {
  conname?: string;
  indexElems?: Node[];
  location?: number;
  whereClause?: Node;
}

export interface InferenceElem {
  expr?: Node;
  infercollid?: number;
  inferopclass?: number;
  xpr?: Node;
}

export interface InlineCodeBlock {
  atomic?: boolean;
  langIsTrusted?: boolean;
  langOid?: number;
  source_text?: string;
}

export interface InsertStmt {
  cols?: InsertStmt_cols[];
  onConflictClause?: { OnConflictClause: OnConflictClause };
  override?: OverridingKind;
  relation?: { RangeVar: RangeVar };
  returningList?: InsertStmt_returningList[];
  selectStmt?: InsertStmt_selectStmt;
  withClause?: { WithClause: WithClause };
}

export interface Integer {
  ival?: number;
}

export interface IntList {
  items?: Node[];
}

export interface IntoClause {
  accessMethod?: string;
  colNames?: Node[];
  onCommit?: OnCommitAction;
  options?: Node[];
  rel?: { RangeVar: RangeVar };
  skipData?: boolean;
  tableSpaceName?: string;
  viewQuery?: Node;
}

export interface JoinExpr {
  alias?: { Alias: Alias };
  isNatural?: boolean;
  join_using_alias?: { Alias: Alias };
  jointype?: JoinType;
  larg?: JoinExpr_larg;
  quals?: JoinExpr_quals;
  rarg?: JoinExpr_rarg;
  rtindex?: number;
  usingClause?: JoinExpr_usingClause[];
}

export interface JsonAggConstructor {
  agg_filter?: Node;
  agg_order?: Node[];
  location?: number;
  output?: { JsonOutput: JsonOutput };
  over?: { WindowDef: WindowDef };
}

export interface JsonArgument {
  name?: string;
  val?: { JsonValueExpr: JsonValueExpr };
}

export interface JsonArrayAgg {
  absent_on_null?: boolean;
  arg?: { JsonValueExpr: JsonValueExpr };
  constructor?: { JsonAggConstructor: JsonAggConstructor };
}

export interface JsonArrayConstructor {
  absent_on_null?: boolean;
  exprs?: JsonArrayConstructor_exprs[];
  location?: number;
  output?: { JsonOutput: JsonOutput };
}

export interface JsonArrayQueryConstructor {
  absent_on_null?: boolean;
  format?: { JsonFormat: JsonFormat };
  location?: number;
  output?: { JsonOutput: JsonOutput };
  query?: JsonArrayQueryConstructor_query;
}

export interface JsonBehavior {
  btype?: JsonBehaviorType;
  coerce?: boolean;
  expr?: Node;
  location?: number;
}

export interface JsonConstructorExpr {
  absent_on_null?: boolean;
  args?: Node[];
  coercion?: Node;
  func?: Node;
  location?: number;
  returning?: { JsonReturning: JsonReturning };
  type?: JsonConstructorType;
  unique?: boolean;
  xpr?: Node;
}

export interface JsonExpr {
  collation?: number;
  column_name?: string;
  format?: { JsonFormat: JsonFormat };
  formatted_expr?: Node;
  location?: number;
  omit_quotes?: boolean;
  on_empty?: { JsonBehavior: JsonBehavior };
  on_error?: { JsonBehavior: JsonBehavior };
  op?: JsonExprOp;
  passing_names?: Node[];
  passing_values?: Node[];
  path_spec?: Node;
  returning?: { JsonReturning: JsonReturning };
  use_io_coercion?: boolean;
  use_json_coercion?: boolean;
  wrapper?: JsonWrapper;
  xpr?: Node;
}

export interface JsonFormat {
  encoding?: JsonEncoding;
  format_type?: JsonFormatType;
  location?: number;
}

export interface JsonFuncExpr {
  column_name?: string;
  context_item?: { JsonValueExpr: JsonValueExpr };
  location?: number;
  on_empty?: { JsonBehavior: JsonBehavior };
  on_error?: { JsonBehavior: JsonBehavior };
  op?: JsonExprOp;
  output?: { JsonOutput: JsonOutput };
  passing?: JsonFuncExpr_passing[];
  pathspec?: JsonFuncExpr_pathspec;
  quotes?: JsonQuotes;
  wrapper?: JsonWrapper;
}

export interface JsonIsPredicate {
  expr?: JsonIsPredicate_expr;
  format?: { JsonFormat: JsonFormat };
  item_type?: JsonValueType;
  location?: number;
  unique_keys?: boolean;
}

export interface JsonKeyValue {
  key?: JsonKeyValue_key;
  value?: { JsonValueExpr: JsonValueExpr };
}

export interface JsonObjectAgg {
  absent_on_null?: boolean;
  arg?: { JsonKeyValue: JsonKeyValue };
  constructor?: { JsonAggConstructor: JsonAggConstructor };
  unique?: boolean;
}

export interface JsonObjectConstructor {
  absent_on_null?: boolean;
  exprs?: JsonObjectConstructor_exprs[];
  location?: number;
  output?: { JsonOutput: JsonOutput };
  unique?: boolean;
}

export interface JsonOutput {
  returning?: { JsonReturning: JsonReturning };
  typeName?: { TypeName: TypeName };
}

export interface JsonParseExpr {
  expr?: { JsonValueExpr: JsonValueExpr };
  location?: number;
  output?: { JsonOutput: JsonOutput };
  unique_keys?: boolean;
}

export interface JsonReturning {
  format?: { JsonFormat: JsonFormat };
  typid?: number;
  typmod?: number;
}

export interface JsonScalarExpr {
  expr?: JsonScalarExpr_expr;
  location?: number;
  output?: { JsonOutput: JsonOutput };
}

export interface JsonSerializeExpr {
  expr?: { JsonValueExpr: JsonValueExpr };
  location?: number;
  output?: { JsonOutput: JsonOutput };
}

export interface JsonTable {
  alias?: { Alias: Alias };
  columns?: JsonTable_columns[];
  context_item?: { JsonValueExpr: JsonValueExpr };
  lateral?: boolean;
  location?: number;
  on_error?: { JsonBehavior: JsonBehavior };
  passing?: JsonTable_passing[];
  pathspec?: { JsonTablePathSpec: JsonTablePathSpec };
}

export interface JsonTableColumn {
  coltype?: JsonTableColumnType;
  columns?: JsonTableColumn_columns[];
  format?: { JsonFormat: JsonFormat };
  location?: number;
  name?: string;
  on_empty?: { JsonBehavior: JsonBehavior };
  on_error?: { JsonBehavior: JsonBehavior };
  pathspec?: { JsonTablePathSpec: JsonTablePathSpec };
  quotes?: JsonQuotes;
  typeName?: { TypeName: TypeName };
  wrapper?: JsonWrapper;
}

export interface JsonTablePath {
  name?: string;
}

export interface JsonTablePathScan {
  child?: Node;
  colMax?: number;
  colMin?: number;
  errorOnError?: boolean;
  path?: { JsonTablePath: JsonTablePath };
  plan?: Node;
}

export interface JsonTablePathSpec {
  location?: number;
  name?: string;
  name_location?: number;
  string?: Node;
}

export interface JsonTableSiblingJoin {
  lplan?: Node;
  plan?: Node;
  rplan?: Node;
}

export interface JsonValueExpr {
  format?: { JsonFormat: JsonFormat };
  formatted_expr?: Node;
  raw_expr?: JsonValueExpr_raw_expr;
}

export interface List {
  items?: List_items[];
}

export interface ListenStmt {
  conditionname?: string;
}

export interface LoadStmt {
  filename?: string;
}

export interface LockingClause {
  lockedRels?: LockingClause_lockedRels[];
  strength?: LockClauseStrength;
  waitPolicy?: LockWaitPolicy;
}

export interface LockStmt {
  mode?: number;
  nowait?: boolean;
  relations?: LockStmt_relations[];
}

export interface MergeAction {
  commandType?: CmdType;
  matchKind?: MergeMatchKind;
  override?: OverridingKind;
  qual?: Node;
  targetList?: Node[];
  updateColnos?: Node[];
}

export interface MergeStmt {
  joinCondition?: MergeStmt_joinCondition;
  mergeWhenClauses?: MergeStmt_mergeWhenClauses[];
  relation?: { RangeVar: RangeVar };
  returningList?: MergeStmt_returningList[];
  sourceRelation?: MergeStmt_sourceRelation;
  withClause?: { WithClause: WithClause };
}

export interface MergeSupportFunc {
  location?: number;
  msfcollid?: number;
  msftype?: number;
  xpr?: Node;
}

export interface MergeWhenClause {
  commandType?: CmdType;
  condition?: MergeWhenClause_condition;
  matchKind?: MergeMatchKind;
  override?: OverridingKind;
  targetList?: MergeWhenClause_targetList[];
  values?: MergeWhenClause_values[];
}

export interface MinMaxExpr {
  args?: MinMaxExpr_args[];
  inputcollid?: number;
  location?: number;
  minmaxcollid?: number;
  minmaxtype?: number;
  op?: MinMaxOp;
  xpr?: Node;
}

export interface MultiAssignRef {
  colno?: number;
  ncolumns?: number;
  source?: MultiAssignRef_source;
}

export interface NamedArgExpr {
  arg?: NamedArgExpr_arg;
  argnumber?: number;
  location?: number;
  name?: string;
  xpr?: Node;
}

export interface NextValueExpr {
  seqid?: number;
  typeId?: number;
  xpr?: Node;
}

export interface NotifyStmt {
  conditionname?: string;
  payload?: string;
}

export interface NullIfExpr {
  args?: Node[];
  inputcollid?: number;
  location?: number;
  opcollid?: number;
  opno?: number;
  opresulttype?: number;
  opretset?: boolean;
  xpr?: Node;
}

export interface NullTest {
  arg?: NullTest_arg;
  argisrow?: boolean;
  location?: number;
  nulltesttype?: NullTestType;
  xpr?: Node;
}

export interface ObjectWithArgs {
  args_unspecified?: boolean;
  objargs?: ObjectWithArgs_objargs[];
  objfuncargs?: ObjectWithArgs_objfuncargs[];
  objname?: ObjectWithArgs_objname[];
}

export interface OidList {
  items?: Node[];
}

export interface OnConflictClause {
  action?: OnConflictAction;
  infer?: { InferClause: InferClause };
  location?: number;
  targetList?: Node[];
  whereClause?: Node;
}

export interface OnConflictExpr {
  action?: OnConflictAction;
  arbiterElems?: Node[];
  arbiterWhere?: Node;
  constraint?: number;
  exclRelIndex?: number;
  exclRelTlist?: Node[];
  onConflictSet?: Node[];
  onConflictWhere?: Node;
}

export interface OpExpr {
  args?: Node[];
  inputcollid?: number;
  location?: number;
  opcollid?: number;
  opno?: number;
  opresulttype?: number;
  opretset?: boolean;
  xpr?: Node;
}

export interface Param {
  location?: number;
  paramcollid?: number;
  paramid?: number;
  paramkind?: ParamKind;
  paramtype?: number;
  paramtypmod?: number;
  xpr?: Node;
}

export interface ParamRef {
  location?: number;
  number?: number;
}

export interface ParseResult {
  stmts?: ({ RawStmt: RawStmt })[];
  version?: number;
}

export interface PartitionBoundSpec {
  is_default?: boolean;
  listdatums?: Node[];
  location?: number;
  lowerdatums?: Node[];
  modulus?: number;
  remainder?: number;
  strategy?: string;
  upperdatums?: Node[];
}

export interface PartitionCmd {
  bound?: { PartitionBoundSpec: PartitionBoundSpec };
  concurrent?: boolean;
  name?: { RangeVar: RangeVar };
}

export interface PartitionElem {
  collation?: PartitionElem_collation[];
  expr?: PartitionElem_expr;
  location?: number;
  name?: string;
  opclass?: PartitionElem_opclass[];
}

export interface PartitionRangeDatum {
  kind?: PartitionRangeDatumKind;
  location?: number;
  value?: Node;
}

export interface PartitionSpec {
  location?: number;
  partParams?: Node[];
  strategy?: PartitionStrategy;
}

export interface PLAssignStmt {
  indirection?: Node[];
  location?: number;
  name?: string;
  nnames?: number;
  val?: { SelectStmt: SelectStmt };
}

export interface PrepareStmt {
  argtypes?: PrepareStmt_argtypes[];
  name?: string;
  query?: PrepareStmt_query;
}

export interface PublicationObjSpec {
  location?: number;
  name?: string;
  pubobjtype?: PublicationObjSpecType;
  pubtable?: { PublicationTable: PublicationTable };
}

export interface PublicationTable {
  columns?: Node[];
  relation?: { RangeVar: RangeVar };
  whereClause?: Node;
}

export interface Query {
  canSetTag?: boolean;
  commandType?: CmdType;
  constraintDeps?: Node[];
  cteList?: Node[];
  distinctClause?: Node[];
  groupClause?: Node[];
  groupDistinct?: boolean;
  groupingSets?: Node[];
  hasAggs?: boolean;
  hasDistinctOn?: boolean;
  hasForUpdate?: boolean;
  hasModifyingCTE?: boolean;
  hasRecursive?: boolean;
  hasRowSecurity?: boolean;
  hasSubLinks?: boolean;
  hasTargetSRFs?: boolean;
  hasWindowFuncs?: boolean;
  havingQual?: Node;
  isReturn?: boolean;
  jointree?: { FromExpr: FromExpr };
  limitCount?: Node;
  limitOffset?: Node;
  limitOption?: LimitOption;
  mergeActionList?: Node[];
  mergeJoinCondition?: Node;
  mergeTargetRelation?: number;
  onConflict?: { OnConflictExpr: OnConflictExpr };
  override?: OverridingKind;
  querySource?: QuerySource;
  resultRelation?: number;
  returningList?: Node[];
  rowMarks?: Node[];
  rtable?: Node[];
  rteperminfos?: Node[];
  setOperations?: Node;
  sortClause?: Node[];
  stmt_len?: number;
  stmt_location?: number;
  targetList?: Node[];
  utilityStmt?: Node;
  windowClause?: Node[];
  withCheckOptions?: Node[];
}

export interface RangeFunction {
  alias?: { Alias: Alias };
  coldeflist?: RangeFunction_coldeflist[];
  functions?: RangeFunction_functions[];
  is_rowsfrom?: boolean;
  lateral?: boolean;
  ordinality?: boolean;
}

export interface RangeSubselect {
  alias?: { Alias: Alias };
  lateral?: boolean;
  subquery?: RangeSubselect_subquery;
}

export interface RangeTableFunc {
  alias?: { Alias: Alias };
  columns?: RangeTableFunc_columns[];
  docexpr?: RangeTableFunc_docexpr;
  lateral?: boolean;
  location?: number;
  namespaces?: RangeTableFunc_namespaces[];
  rowexpr?: RangeTableFunc_rowexpr;
}

export interface RangeTableFuncCol {
  coldefexpr?: RangeTableFuncCol_coldefexpr;
  colexpr?: RangeTableFuncCol_colexpr;
  colname?: string;
  for_ordinality?: boolean;
  is_not_null?: boolean;
  location?: number;
  typeName?: { TypeName: TypeName };
}

export interface RangeTableSample {
  args?: RangeTableSample_args[];
  location?: number;
  method?: RangeTableSample_method[];
  relation?: RangeTableSample_relation;
  repeatable?: RangeTableSample_repeatable;
}

export interface RangeTblEntry {
  alias?: { Alias: Alias };
  colcollations?: Node[];
  coltypes?: Node[];
  coltypmods?: Node[];
  ctelevelsup?: number;
  ctename?: string;
  enrname?: string;
  enrtuples?: number;
  eref?: { Alias: Alias };
  funcordinality?: boolean;
  functions?: Node[];
  inFromCl?: boolean;
  inh?: boolean;
  join_using_alias?: { Alias: Alias };
  joinaliasvars?: Node[];
  joinleftcols?: Node[];
  joinmergedcols?: number;
  joinrightcols?: Node[];
  jointype?: JoinType;
  lateral?: boolean;
  perminfoindex?: number;
  relid?: number;
  relkind?: string;
  rellockmode?: number;
  rtekind?: RTEKind;
  security_barrier?: boolean;
  securityQuals?: Node[];
  self_reference?: boolean;
  subquery?: { Query: Query };
  tablefunc?: { TableFunc: TableFunc };
  tablesample?: { TableSampleClause: TableSampleClause };
  values_lists?: Node[];
}

export interface RangeTblFunction {
  funccolcollations?: Node[];
  funccolcount?: number;
  funccolnames?: Node[];
  funccoltypes?: Node[];
  funccoltypmods?: Node[];
  funcexpr?: Node;
  funcparams?: number[];
}

export interface RangeTblRef {
  rtindex?: number;
}

export interface RangeVar {
  alias?: { Alias: Alias };
  catalogname?: string;
  inh?: boolean;
  location?: number;
  relname?: string;
  relpersistence?: string;
  schemaname?: string;
}

export interface RawStmt {
  stmt?: Node;
  stmt_len?: number;
  stmt_location?: number;
}

export interface ReassignOwnedStmt {
  newrole?: { RoleSpec: RoleSpec };
  roles?: ReassignOwnedStmt_roles[];
}

export interface RefreshMatViewStmt {
  concurrent?: boolean;
  relation?: { RangeVar: RangeVar };
  skipData?: boolean;
}

export interface ReindexStmt {
  kind?: ReindexObjectType;
  name?: string;
  params?: ReindexStmt_params[];
  relation?: { RangeVar: RangeVar };
}

export interface RelabelType {
  arg?: Node;
  location?: number;
  relabelformat?: CoercionForm;
  resultcollid?: number;
  resulttype?: number;
  resulttypmod?: number;
  xpr?: Node;
}

export interface RenameStmt {
  behavior?: DropBehavior;
  missing_ok?: boolean;
  newname?: string;
  object?: RenameStmt_object;
  relation?: { RangeVar: RangeVar };
  relationType?: ObjectType;
  renameType?: ObjectType;
  subname?: string;
}

export interface ReplicaIdentityStmt {
  identity_type?: string;
  name?: string;
}

export interface ResTarget {
  indirection?: ResTarget_indirection[];
  location?: number;
  name?: string;
  val?: ResTarget_val;
}

export interface ReturnStmt {
  returnval?: ReturnStmt_returnval;
}

export interface RoleSpec {
  location?: number;
  rolename?: string;
  roletype?: RoleSpecType;
}

export interface RowCompareExpr {
  inputcollids?: Node[];
  largs?: Node[];
  opfamilies?: Node[];
  opnos?: Node[];
  rargs?: Node[];
  rctype?: RowCompareType;
  xpr?: Node;
}

export interface RowExpr {
  args?: RowExpr_args[];
  colnames?: Node[];
  location?: number;
  row_format?: CoercionForm;
  row_typeid?: number;
  xpr?: Node;
}

export interface RowMarkClause {
  pushedDown?: boolean;
  rti?: number;
  strength?: LockClauseStrength;
  waitPolicy?: LockWaitPolicy;
}

export interface RTEPermissionInfo {
  checkAsUser?: number;
  inh?: boolean;
  insertedCols?: number[];
  relid?: number;
  requiredPerms?: number;
  selectedCols?: number[];
  updatedCols?: number[];
}

export interface RuleStmt {
  actions?: RuleStmt_actions[];
  event?: CmdType;
  instead?: boolean;
  relation?: { RangeVar: RangeVar };
  replace?: boolean;
  rulename?: string;
  whereClause?: RuleStmt_whereClause;
}

export interface ScalarArrayOpExpr {
  args?: Node[];
  inputcollid?: number;
  location?: number;
  opno?: number;
  useOr?: boolean;
  xpr?: Node;
}

export interface ScanResult {
  tokens?: ({ ScanToken: ScanToken })[];
  version?: number;
}

export interface ScanToken {
  end?: number;
  keywordKind?: KeywordKind;
  start?: number;
  token?: Token;
}

export interface SecLabelStmt {
  label?: string;
  object?: SecLabelStmt_object;
  objtype?: ObjectType;
  provider?: string;
}

export interface SelectStmt {
  all?: boolean;
  distinctClause?: SelectStmt_distinctClause[];
  fromClause?: SelectStmt_fromClause[];
  groupClause?: SelectStmt_groupClause[];
  groupDistinct?: boolean;
  havingClause?: SelectStmt_havingClause;
  intoClause?: { IntoClause: IntoClause };
  larg?: { SelectStmt: SelectStmt };
  limitCount?: SelectStmt_limitCount;
  limitOffset?: SelectStmt_limitOffset;
  limitOption?: LimitOption;
  lockingClause?: SelectStmt_lockingClause[];
  op?: SetOperation;
  rarg?: { SelectStmt: SelectStmt };
  sortClause?: SelectStmt_sortClause[];
  targetList?: SelectStmt_targetList[];
  valuesLists?: SelectStmt_valuesLists[];
  whereClause?: SelectStmt_whereClause;
  windowClause?: SelectStmt_windowClause[];
  withClause?: { WithClause: WithClause };
}

export interface SetOperationStmt {
  all?: boolean;
  colCollations?: Node[];
  colTypes?: Node[];
  colTypmods?: Node[];
  groupClauses?: Node[];
  larg?: Node;
  op?: SetOperation;
  rarg?: Node;
}

export interface SetToDefault {
  collation?: number;
  location?: number;
  typeId?: number;
  typeMod?: number;
  xpr?: Node;
}

export interface SinglePartitionSpec {
}

export interface SortBy {
  location?: number;
  node?: SortBy_node;
  sortby_dir?: SortByDir;
  sortby_nulls?: SortByNulls;
  useOp?: SortBy_useOp[];
}

export interface SortGroupClause {
  eqop?: number;
  hashable?: boolean;
  nulls_first?: boolean;
  sortop?: number;
  tleSortGroupRef?: number;
}

export interface SQLValueFunction {
  location?: number;
  op?: SQLValueFunctionOp;
  type?: number;
  typmod?: number;
  xpr?: Node;
}

export interface StatsElem {
  expr?: StatsElem_expr;
  name?: string;
}

export interface String {
  sval?: string;
}

export interface SubLink {
  location?: number;
  operName?: SubLink_operName[];
  subLinkId?: number;
  subLinkType?: SubLinkType;
  subselect?: SubLink_subselect;
  testexpr?: SubLink_testexpr;
  xpr?: Node;
}

export interface SubPlan {
  args?: Node[];
  firstColCollation?: number;
  firstColType?: number;
  firstColTypmod?: number;
  parallel_safe?: boolean;
  paramIds?: Node[];
  parParam?: Node[];
  per_call_cost?: number;
  plan_id?: number;
  plan_name?: string;
  setParam?: Node[];
  startup_cost?: number;
  subLinkType?: SubLinkType;
  testexpr?: Node;
  unknownEqFalse?: boolean;
  useHashTable?: boolean;
  xpr?: Node;
}

export interface SubscriptingRef {
  refassgnexpr?: Node;
  refcollid?: number;
  refcontainertype?: number;
  refelemtype?: number;
  refexpr?: Node;
  reflowerindexpr?: Node[];
  refrestype?: number;
  reftypmod?: number;
  refupperindexpr?: Node[];
  xpr?: Node;
}

export interface TableFunc {
  colcollations?: Node[];
  coldefexprs?: Node[];
  colexprs?: Node[];
  colnames?: Node[];
  coltypes?: Node[];
  coltypmods?: Node[];
  colvalexprs?: Node[];
  docexpr?: Node;
  functype?: TableFuncType;
  location?: number;
  notnulls?: number[];
  ns_names?: Node[];
  ns_uris?: Node[];
  ordinalitycol?: number;
  passingvalexprs?: Node[];
  plan?: Node;
  rowexpr?: Node;
}

export interface TableLikeClause {
  options?: number;
  relation?: { RangeVar: RangeVar };
  relationOid?: number;
}

export interface TableSampleClause {
  args?: Node[];
  repeatable?: Node;
  tsmhandler?: number;
}

export interface TargetEntry {
  expr?: Node;
  resjunk?: boolean;
  resname?: string;
  resno?: number;
  resorigcol?: number;
  resorigtbl?: number;
  ressortgroupref?: number;
  xpr?: Node;
}

export interface TransactionStmt {
  chain?: boolean;
  gid?: string;
  kind?: TransactionStmtKind;
  location?: number;
  options?: TransactionStmt_options[];
  savepoint_name?: string;
}

export interface TriggerTransition {
  isNew?: boolean;
  isTable?: boolean;
  name?: string;
}

export interface TruncateStmt {
  behavior?: DropBehavior;
  relations?: TruncateStmt_relations[];
  restart_seqs?: boolean;
}

export interface TypeCast {
  arg?: TypeCast_arg;
  location?: number;
  typeName?: { TypeName: TypeName };
}

export interface TypeName {
  arrayBounds?: TypeName_arrayBounds[];
  location?: number;
  names?: TypeName_names[];
  pct_type?: boolean;
  setof?: boolean;
  typemod?: number;
  typeOid?: number;
  typmods?: TypeName_typmods[];
}

export interface UnlistenStmt {
  conditionname?: string;
}

export interface UpdateStmt {
  fromClause?: UpdateStmt_fromClause[];
  relation?: { RangeVar: RangeVar };
  returningList?: UpdateStmt_returningList[];
  targetList?: UpdateStmt_targetList[];
  whereClause?: UpdateStmt_whereClause;
  withClause?: { WithClause: WithClause };
}

export interface VacuumRelation {
  oid?: number;
  relation?: { RangeVar: RangeVar };
  va_cols?: VacuumRelation_va_cols[];
}

export interface VacuumStmt {
  is_vacuumcmd?: boolean;
  options?: VacuumStmt_options[];
  rels?: VacuumStmt_rels[];
}

export interface Var {
  location?: number;
  varattno?: number;
  varcollid?: number;
  varlevelsup?: number;
  varno?: number;
  varnullingrels?: number[];
  vartype?: number;
  vartypmod?: number;
  xpr?: Node;
}

export interface VariableSetStmt {
  args?: VariableSetStmt_args[];
  is_local?: boolean;
  kind?: VariableSetKind;
  name?: string;
}

export interface VariableShowStmt {
  name?: string;
}

export interface ViewStmt {
  aliases?: ViewStmt_aliases[];
  options?: ViewStmt_options[];
  query?: ViewStmt_query;
  replace?: boolean;
  view?: { RangeVar: RangeVar };
  withCheckOption?: ViewCheckOption;
}

export interface WindowClause {
  copiedOrder?: boolean;
  endInRangeFunc?: number;
  endOffset?: Node;
  frameOptions?: number;
  inRangeAsc?: boolean;
  inRangeColl?: number;
  inRangeNullsFirst?: boolean;
  name?: string;
  orderClause?: Node[];
  partitionClause?: Node[];
  refname?: string;
  startInRangeFunc?: number;
  startOffset?: Node;
  winref?: number;
}

export interface WindowDef {
  endOffset?: WindowDef_endOffset;
  frameOptions?: number;
  location?: number;
  name?: string;
  orderClause?: WindowDef_orderClause[];
  partitionClause?: WindowDef_partitionClause[];
  refname?: string;
  startOffset?: WindowDef_startOffset;
}

export interface WindowFunc {
  aggfilter?: Node;
  args?: Node[];
  inputcollid?: number;
  location?: number;
  runCondition?: Node[];
  winagg?: boolean;
  wincollid?: number;
  winfnoid?: number;
  winref?: number;
  winstar?: boolean;
  wintype?: number;
  xpr?: Node;
}

export interface WindowFuncRunCondition {
  arg?: Node;
  inputcollid?: number;
  opno?: number;
  wfunc_left?: boolean;
  xpr?: Node;
}

export interface WithCheckOption {
  cascaded?: boolean;
  kind?: WCOKind;
  polname?: string;
  qual?: Node;
  relname?: string;
}

export interface WithClause {
  ctes?: Node[];
  location?: number;
  recursive?: boolean;
}

export interface XmlExpr {
  arg_names?: Node[];
  args?: XmlExpr_args[];
  indent?: boolean;
  location?: number;
  name?: string;
  named_args?: XmlExpr_named_args[];
  op?: XmlExprOp;
  type?: number;
  typmod?: number;
  xmloption?: XmlOptionType;
  xpr?: Node;
}

export interface XmlSerialize {
  expr?: XmlSerialize_expr;
  indent?: boolean;
  location?: number;
  typeName?: { TypeName: TypeName };
  xmloption?: XmlOptionType;
}
