-- Ref: constructive-io/pgsql-parser#348
-- Ref: constructive-io/pgsql-parser#350
ALTER TABLE ONLY public.measurement ATTACH PARTITION public.measurement_y2024 FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
ALTER TABLE ONLY public.measurement DETACH PARTITION public.measurement_y2024;
ALTER TABLE public.measurement DETACH PARTITION public.measurement_y2024 CONCURRENTLY;
ALTER TABLE ONLY measurement ATTACH PARTITION measurement_y2024 FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
ALTER TABLE ONLY o ATTACH PARTITION o_p FOR VALUES WITH (MODULUS 4, REMAINDER 0);
ALTER TABLE ONLY o ATTACH PARTITION o_p FOR VALUES WITH (MODULUS 4, REMAINDER 1);
ALTER TABLE ONLY s.o ATTACH PARTITION s.o_p DEFAULT;
ALTER TABLE ONLY o ATTACH PARTITION o_p FOR VALUES IN (1, 2);
CREATE TABLE o_p0 PARTITION OF o FOR VALUES WITH (MODULUS 4, REMAINDER 0);
