-- PARTITION OF with column options and hash bounds
CREATE TABLE p1 PARTITION OF parent (f3 WITH OPTIONS GENERATED ALWAYS AS IDENTITY) FOR VALUES FROM ('2016-11-01') TO ('2016-12-01');
CREATE TABLE p1 PARTITION OF parent (a NOT NULL, b DEFAULT 1, CONSTRAINT p1_chk CHECK (a > 0)) FOR VALUES IN (1, 2);
CREATE TABLE p1 PARTITION OF parent FOR VALUES WITH (MODULUS 2, REMAINDER 0);
CREATE TABLE p1 PARTITION OF parent FOR VALUES WITH (MODULUS 4, REMAINDER 3);
CREATE TABLE p1 PARTITION OF parent (a WITH OPTIONS NOT NULL) FOR VALUES WITH (MODULUS 2, REMAINDER 1);
CREATE TABLE p1 PARTITION OF parent DEFAULT;
CREATE TABLE p1 PARTITION OF parent (a NOT NULL) DEFAULT;
CREATE TABLE p1 PARTITION OF parent FOR VALUES FROM (MINVALUE) TO (MAXVALUE) PARTITION BY HASH (b);
ALTER TABLE parent ATTACH PARTITION p1 FOR VALUES WITH (MODULUS 2, REMAINDER 0);
ALTER TABLE parent ATTACH PARTITION p1 DEFAULT;
-- CREATE TABLE AS option placement/quoting
CREATE TABLE tas_case WITH ("Fillfactor" = 10) AS SELECT 1 a;
CREATE TABLE tas WITH (fillfactor = 10, autovacuum_enabled = false) AS SELECT 1 a;
CREATE TEMP TABLE tas ON COMMIT DROP AS SELECT 1 a;
CREATE TABLE tas (x, y) WITH (fillfactor = 50) TABLESPACE pg_default AS SELECT 1, 2 WITH NO DATA;
CREATE TABLE tas USING heap WITH (fillfactor = 50) AS SELECT 1 a;
CREATE MATERIALIZED VIEW mv WITH (fillfactor = 50) AS SELECT 1 a WITH NO DATA;
-- reloption quoting in CREATE TABLE
CREATE TABLE t (a int) WITH ("Fillfactor" = 10, toast.autovacuum_enabled = false);
