// DO NOT EDIT BY HAND — generated by scripts/make-kitchen-sink.ts
import { readFileSync } from 'fs';
import { join } from 'path';

import { FixtureTestUtils } from '../../test-utils';

const manifest: Record<string, string[]> = JSON.parse(
  readFileSync(join(__dirname, 'fixtures.json'), 'utf-8')
);
const fixtures = new FixtureTestUtils(17, 18);

describe('17-18', () => {
  it.each(Object.entries(manifest))('%s', async (_name, tests) => {
    await fixtures.runFixtureTests(tests);
  });
});
